feat: select into offline data
4paradigm/OpenMLDB pull request #1030
Opened 2022-01-05 09:58 UTC by vagetablechicken

Closes #731 
If set offline mode, `select into` will call `ExportOfflineData` rpc of taskmanager, get offline data, and then write to file.

2022-01-05 10:21 UTC, tobegit3hub requested changes

2022-01-05 10:21 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/SelectIntoPlan.scala
> +    input.getDf().printSchema()
Is this for test?

2022-01-05 10:21 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/TestSelectIntoPlan.scala
> +    val filePath = "/tmp/select_into_test"
Maybe use "file:///tmp/select_into_test"

2022-01-05 10:26 UTC, vagetablechicken commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/SelectIntoPlan.scala
> +    input.getDf().printSchema()
yes, forgot to delete.

2022-01-05 10:26 UTC, vagetablechicken commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/TestSelectIntoPlan.scala
> +    val filePath = "/tmp/select_into_test"
ok

2022-01-05 10:29 UTC, tobegit3hub approved these changes
LGTM

2022-01-05 11:06 UTC, dl239 approved these changes

2022-01-05 14:55 UTC, merged

2022-01-11 08:09 UTC, vagetablechicken commented
![](https://github.trello.services/images/mini-trello-icon.png) [data import for offline and online in the task manager](https://trello.com/c/OqReyYcD/23-data-import-for-offline-and-online-in-the-task-manager)