fix: importing CSV file in offline reate files with correct schema
4paradigm/OpenMLDB pull request #1122
Opened 2022-01-19 10:21 UTC by yabg-shuai666

close #1100

2022-01-20 14:35 UTC, lumianph commented
@tobegit3hub let's merge this PR ASAP, and then let the user in wechat know when it is fixed.

2022-01-21 03:03 UTC, tobegit3hub requested changes

2022-01-21 03:03 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/LoadDataPlan.scala
> +        var struct = new StructType
Please add an unit test for this added function.

2022-01-21 06:42 UTC, tobegit3hub approved these changes
LGTM

2022-01-21 06:42 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/LoadDataPlan.scala
> +        var struct = new StructType
We will add tests later.

2022-01-24 03:53 UTC, vagetablechicken approved these changes

2022-01-24 03:54 UTC, merged