fix: fixed always yield true if statement
4paradigm/OpenMLDB pull request #1379
Opened 2022-03-04 08:16 UTC by wuteek

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

This statement always returns true
fixes taskmanager: compare int with null #1377

2022-03-04 19:30 UTC, wuteek commented
I was wondering if I was able to get some help passing the coverage check? I am new to contributing

2022-03-05 01:50 UTC, lumianph commented
> I was wondering if I was able to get some help passing the coverage check? I am new to contributing

No worry about that. It failed due to issues of some of our test cases (not related to your code).

2022-03-05 02:25 UTC, vagetablechicken commented on java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/spark/SparkJobManager.scala
> +    if ((TaskManagerConfig.SPARK_YARN_MAXAPPATTEMPTS : java.lang.Integer) != null) {
`SPARK_YARN_MAXAPPATTEMPTS` is int, not Integer, no need to check if null

2022-03-05 02:34 UTC, vagetablechicken requested changes
You could do this:
```
if SPARK_YARN_MAXAPPATTEMPTS >= 1:
    setConf
```

2022-03-05 05:51 UTC, wuteek commented
> You could do this:
> 
> ```
> if SPARK_YARN_MAXAPPATTEMPTS >= 1:
>     setConf
> ```

Hello, I pushed with the recommendations that you gave. Please let me know if any further issues occur. Thank you!

2022-03-05 23:03 UTC, lumianph approved these changes
LGTM

2022-03-06 08:00 UTC, vagetablechicken approved these changes

2022-03-06 08:01 UTC, merged