docs: Add English version of milestone.md
4paradigm/OpenMLDB pull request #1512
Opened 2022-03-25 10:15 UTC by L-Y-L

docs: Add English version of milestone.md 
#1489

2022-03-25 10:15 UTC, L-Y-L commented
fixed #1489

2022-03-29 14:58 UTC, lumianph requested changes

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +# OpenMLDB development history
The Evolution of OpenMLDB

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +## 1. From commercial closed source to community open source
capitalize the first letter of words for a title

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +OpenMLDB originated as an internal commercial product of [Fourth Paradigm](https://www.4paradigm.com), an industry-leading artificial intelligence platform and service provider. The commercial AI pla
Fourth Paradigm => 4Paradigm

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +In 2021, the core development team of OpenMLDB will abstract, enhance, and add many community-friendly features to the core modules of data governance and feature engineering in the 4Paradigm interna
In 2021, the core development team of OpenMLDB will abstract, enhance, and add many community-friendly features to the core modules of data governance and feature engineering in the 4Paradigm internal commercial products.
=>
In 2021, the development team abstracted, enhanced, and added many community-friendly features to the core modules of data governance and feature engineering in the commercial products, and finally made it publicly available as an opensource project OpenMLDB.

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2019.8: The first retail industry user, Yum!
Yum! => Yum China

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2020.12: The cumulative number of landing scenes exceeds 100
landing scenes => real-world applications

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2021.6: Machine learning database OpenMLDB officially announced open source, providing enterprise-level FeatureOps full-stack solution
enterprise-level FeatureOps full-stack solution
enterprise-grade full-stack FeatureOps solution

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2021.7: v0.2.0 released, supports RestAPI access, optimized code style and comments
supports => supporting
 optimized code style and comments => code style and comments improved

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2021.8: Recognized by Gitee and awarded the title of GVP (Gitee Most Valuable Project, the most valuable open source project)
delete ", the most valuable open source project"

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2021.9: The first open source community enterprise user, [Akulaku](https://www.akulaku.com/)
delete "open source"

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2021.11: v0.3.0 released, supporting single-machine deployment mode for rapid deployment
single-machine deployment mode
=>
the standalone deployment

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +- 2022.1: v0.4.0 is released, enhancing the development experience with SQL as the core, and introducing an online monitoring module
v0.4.0 released, enhancing the SQL-centric development experience, introducing the new online monitoring module

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +The future development of OpenMLDB will firmly follow the path of community-based open source and openness, in order to benefit more enterprises and developers. In the future, in terms of technology,
delete "openness"
delete ", in order "

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +The future development of OpenMLDB will firmly follow the path of community-based open source and openness, in order to benefit more enterprises and developers. In the future, in terms of technology,
we will accelerate ecological construction, improve product information,
=>
OpenMLDB will integrate into the open-source ecosystem,

2022-03-29 14:58 UTC, lumianph commented on docs/en/milestones.md
> +The future development of OpenMLDB will firmly follow the path of community-based open source and openness, in order to benefit more enterprises and developers. In the future, in terms of technology,
We hope => we hope

2022-03-31 10:50 UTC, L-Y-L commented on docs/en/milestones.md
> +The future development of OpenMLDB will firmly follow the path of community-based open source and openness, in order to benefit more enterprises and developers. In the future, in terms of technology,
Ok, thank you.

2022-03-31 10:50 UTC, L-Y-L commented on docs/en/milestones.md
> +- 2022.1: v0.4.0 is released, enhancing the development experience with SQL as the core, and introducing an online monitoring module
Ok, thank you.

2022-03-31 10:51 UTC, L-Y-L commented on docs/en/milestones.md
> +- 2021.11: v0.3.0 released, supporting single-machine deployment mode for rapid deployment
Ok, thank you.

2022-03-31 10:51 UTC, L-Y-L commented on docs/en/milestones.md
> +- 2021.9: The first open source community enterprise user, [Akulaku](https://www.akulaku.com/)
Ok, thank you.

2022-03-31 10:51 UTC, cswjd commented on docs/en/milestones.md
> +- 2021.8: Recognized by Gitee and awarded the title of GVP (Gitee Most Valuable Project, the most valuable open source project)
Ok, thank you.

2022-03-31 10:51 UTC, cswjd commented on docs/en/milestones.md
> +- 2021.7: v0.2.0 released, supports RestAPI access, optimized code style and comments
Ok, thank you.

2022-03-31 10:51 UTC, L-Y-L commented on docs/en/milestones.md
> +- 2021.6: Machine learning database OpenMLDB officially announced open source, providing enterprise-level FeatureOps full-stack solution
Ok, thank you.

2022-03-31 10:51 UTC, cswjd commented on docs/en/milestones.md
> +- 2020.12: The cumulative number of landing scenes exceeds 100
Ok, thank you.

2022-03-31 10:51 UTC, cswjd commented on docs/en/milestones.md
> +- 2019.8: The first retail industry user, Yum!
Ok, thank you.

2022-03-31 10:52 UTC, cswjd commented on docs/en/milestones.md
> +In 2021, the core development team of OpenMLDB will abstract, enhance, and add many community-friendly features to the core modules of data governance and feature engineering in the 4Paradigm interna
Ok, thank you.

2022-03-31 10:52 UTC, L-Y-L commented on docs/en/milestones.md
> +OpenMLDB originated as an internal commercial product of [Fourth Paradigm](https://www.4paradigm.com), an industry-leading artificial intelligence platform and service provider. The commercial AI pla
Ok, thank you.

2022-03-31 10:52 UTC, L-Y-L commented on docs/en/milestones.md
> +## 1. From commercial closed source to community open source
Ok, thank you.

2022-03-31 10:52 UTC, L-Y-L commented on docs/en/milestones.md
> +# OpenMLDB development history
Ok, thank you.

2022-04-01 00:43 UTC, lumianph approved these changes
LGTM, thanks

2022-04-01 01:43 UTC, lumianph approved these changes
LGTM

2022-04-01 01:44 UTC, merged