Removes an unused variable and its statement
4paradigm/OpenMLDB pull request #1551
Opened 2022-03-31 04:36 UTC by johndinh391

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
It removes an unused variable and its related statement.

* **What is the current behavior?** (You can also link to an open issue here)
It should resolve Issue #1536.

* **What is the new behavior (if this is a feature change)?**
There should be no new behavior.

2022-04-01 06:26 UTC, tobegit3hub commented on java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/JobInfoManager.scala
> +      catch {
Remove this as well.

2022-04-02 11:45 UTC, aceforeverd requested changes

2022-04-02 11:45 UTC, aceforeverd commented on java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/JobInfoManager.scala
>      try {
looks wired, maybe u can use `try with resource`  alternative in scala: https://www.baeldung.com/scala/try-with-resources

2022-04-06 11:12 UTC, aceforeverd commented on java/openmldb-taskmanager/src/main/scala/com/_4paradigm/openmldb/taskmanager/JobInfoManager.scala
> +    } Using.Manager { use =>
I'm  afraid it is not the correct way to with `Using.Manager`, here we want to automatically close the `pstmt` object in the try block (that in line 155), so u should replace the try block with `Using.Manager`. In my mind, the second try ... catch block is unnecessary

2022-04-08 08:30 UTC, aceforeverd commented
Hi @johndinh391, the PR won't pass the tests. So I guess you should first try to run the related test locally before submit changes.
You can mainly focus on the java/scala tests,  have a look at the workflow job: https://github.com/4paradigm/OpenMLDB/blob/f5fc988a38d0d9b8952155cdfe9d782133502e46/.github/workflows/sdk.yml#L79-L101

In summary, 
1. compile: run in top directory as `make build SQL_JAVASDK_ENABLE=ON`
2. Setup test requirements, as:
     ```bash
          sh steps/ut_zookeeper.sh start
          # replace $SPARK_HOME with the real directory path, u can give whatever u want
          sh steps/download_openmldb_spark.sh $SPARK_HOME
          cd onebox && sh start_onebox.sh && sh start_onebox.sh standalone && cd - || exit
     ```
3. test: `cd java/ && ./mvnw test`
    it will run all tests, but if u are in IDE, u probably find way to run single tests as well

2022-04-26 11:10 UTC, tobegit3hub approved these changes
LGTM

2022-04-26 11:12 UTC, vagetablechicken approved these changes

2022-04-26 11:14 UTC, aceforeverd approved these changes

2022-04-26 11:14 UTC, merged