doc: update changelog
4paradigm/OpenMLDB pull request #1555
Opened 2022-03-31 09:44 UTC by dl239

add v0.4.4 chagelog
#1530

2022-03-31 14:19 UTC, lumianph commented
![image](https://user-images.githubusercontent.com/3725932/161077231-9faa45d8-35c5-4651-8fc4-37421f250b75.png)

add the 044 comparison at the end of CHANGELOG

2022-03-31 14:20 UTC, lumianph requested changes
add the 044 comparison at the end of CHANGELOG

2022-04-01 06:24 UTC, tobegit3hub approved these changes
LGTM

2022-04-01 08:13 UTC, lumianph commented on CHANGELOG.md
> +- Add the `executemany` API in Python SDK (#1402 @hezhaozhao-git )
change this item to:
- Support multiple rows insertion in the Python SDK (#1402 @hezhaozhao-git )

2022-04-02 05:30 UTC, dl239 commented
> add the 044 comparison at the end of CHANGELOG

done

2022-04-02 07:22 UTC, lumianph approved these changes

2022-04-02 07:27 UTC, merged