feat: more aggregator op
4paradigm/OpenMLDB pull request #1583
Opened 2022-04-06 02:54 UTC by nautaa

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
close #1218 
close #1219 
close #1220 
close #1221 
close #1525 

* **What is the new behavior (if this is a feature change)?**

2022-04-06 03:07 UTC, zhanghaohit commented
![](https://github.trello.services/images/mini-trello-icon.png) [long time window - compute engine](https://trello.com/c/XMMF5TXl/6-long-time-window-compute-engine)

2022-04-08 04:17 UTC, zhanghaohit requested changes

2022-04-08 04:17 UTC, zhanghaohit commented on src/codec/codec.cc
> -    *(reinterpret_cast<uint32_t*>(buf_ + VERSION_LENGTH)) = size;
better not to change the behavior of public `SetBuffer` in case of mis-use. 

Maybe we can have a `InitBuffer` to do the initialization. `SetBuffer(int8_t* buf, uint32_t size)` keeps the same, while `SetBuffer(int8_t* buf, uint32_t size, bool need_clear)` do the `buf_` assignment and `InitBuffer`

2022-04-08 04:17 UTC, zhanghaohit commented on src/storage/aggregator.cc
> +            if (aggr_buffer->AggrValEmpty() || strcmp(ch, aggr_val.data) < 0) {
Is ch or aggr_val.data guaranteed to be ended with `\0'?

2022-04-08 04:17 UTC, zhanghaohit commented on src/storage/aggregator.h
> +    virtual bool EncodeAggrVal(const AggrBuffer& buffer, std::string* aggr_val) { return false; }
can make `UpdateAggrVal`  and `EncodeAggrVal` pure abstract in case child class forgot to implement?

2022-04-08 04:17 UTC, zhanghaohit commented on src/storage/aggregator_test.cc
> +        origin_row_view.GetString(4, &ch, &ch_length);
what if it is null
same for `min` ops

2022-04-08 04:17 UTC, zhanghaohit commented on src/storage/aggregator_test.cc
> +    ASSERT_EQ(last_buffer.non_null_cnt, 0);
also add the checking of `non_null_cnt` for other `ops`

2022-04-10 01:23 UTC, zhanghaohit approved these changes
LGTM

2022-04-12 07:11 UTC, dl239 approved these changes

2022-04-12 07:18 UTC, merged