feat: parameter correction of xgboost objective
4paradigm/OpenMLDB pull request #1631
Opened 2022-04-14 15:09 UTC by yabg-shuai666

The configuration names of lightgbm and xgboost objective are different, this time it is changed to binary:logistic. xgboost objective parameter has no binary option.

2022-04-15 06:17 UTC, tobegit3hub approved these changes
LGTM

2022-04-15 07:01 UTC, dl239 approved these changes

2022-04-18 10:15 UTC, vagetablechicken requested changes
I'll test it

2022-04-19 06:44 UTC, vagetablechicken approved these changes

2022-04-19 06:48 UTC, merged