Docs-Check: v0.4 (OpenMLDB Quickstart Page)
4paradigm/OpenMLDB pull request #1678
Opened 2022-04-21 04:45 UTC by TanZiYen

2022-04-24 03:00 UTC, tobegit3hub approved these changes
LGTM

2022-04-25 05:55 UTC, lumianph commented on docs/en/quickstart/openmldb_quickstart.md
> +The workflow of the standalone version of OpenMLDB generally includes several stages: Database and table establishment, data preparation, offline feature extraction, SQL solution online, and online r
Database => database
no need to capitalize after the colon

2022-04-25 05:56 UTC, lumianph commented on docs/en/quickstart/openmldb_quickstart.md
> +The workflow of the cluster version of OpenMLDB generally includes several stages: Database and table creation, offline data preparation, offline feature extraction, SQL solution online, online data
database

2022-04-25 05:57 UTC, lumianph commented on docs/en/quickstart/openmldb_quickstart.md
> +Notice: Warning: According to the default deployment configuration, the http port for apiserver deployment is 9080.
remove "Warning:"

2022-04-25 05:57 UTC, lumianph requested changes
@TanZiYen

2022-04-28 14:44 UTC, lumianph approved these changes

2022-04-28 14:45 UTC, merged