Docs-Check: v0.4 (Maintenance-Operations in CLI Page)
4paradigm/OpenMLDB pull request #1689
Opened 2022-04-21 08:30 UTC by TanZiYen

2022-04-22 13:49 UTC, lumianph commented on docs/en/maintain/cli.md
> -### use
those starting with ### (including the below) are commands, no need to capitalize them, please revert them to the lower cases

2022-04-22 13:52 UTC, lumianph commented on docs/en/maintain/cli.md
> +* table\_name: The table name
this is the description for a specific term, by convention we also no need to capitalize the first word, please help change them back.

2022-04-22 13:53 UTC, lumianph requested changes
pls fix the capitalization for commands and terms

2022-04-24 02:59 UTC, tobegit3hub approved these changes
LGTM

2022-04-25 14:07 UTC, lumianph approved these changes

2022-04-25 14:09 UTC, merged