fix: check `long_windows` option  match window in sql
4paradigm/OpenMLDB pull request #1712
Opened 2022-04-25 11:45 UTC by nautaa

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fix

* **What is the current behavior?** (You can also link to an open issue here)
close #1711 

* **What is the new behavior (if this is a feature change)?**

2022-04-27 02:37 UTC, zhanghaohit requested changes

2022-04-27 02:37 UTC, zhanghaohit commented on src/sdk/sql_cluster_router.cc
> +        }
not exactly like this.

we want to check any `window_name` declared in the `long_windows` options should exist in the window definitions.

2022-04-28 04:14 UTC, zhanghaohit commented on src/sdk/sql_cluster_test.cc
> +    }
"deploy test1 options(long_windows='w_error:1d') select col1,"
                                 " sum(col3) over w1 as w1_sum_col3 from " + base_table +
                                 " WINDOW w1 AS (PARTITION BY col1 ORDER BY col2"
                                 " ROWS_RANGE BETWEEN 20s PRECEDING AND CURRENT ROW);";

maybe add another test if the `window_name` is wrongly put

2022-04-28 09:24 UTC, zhanghaohit commented on src/sdk/sql_cluster_test.cc
> +
fix lint error

2022-04-28 15:30 UTC, zhanghaohit approved these changes
LGTM

2022-05-06 06:45 UTC, dl239 approved these changes

2022-05-06 06:45 UTC, aceforeverd approved these changes

2022-05-06 06:53 UTC, merged