docs: translate the Chinese doc of faq.md into English (#1796)
4paradigm/OpenMLDB pull request #1815
Opened 2022-05-13 04:13 UTC by jmoldyvan

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
make a new faq.md file in the docs/en/maintain folder
-add faq to index rst

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
-translation from chinese faq
-add new file
-add faq to indexrst

2022-05-16 14:19 UTC, lumianph requested changes
@jmoldyvan thank you for your contribution! Are you interested in making more contribution to this project? You may join our slack channel to talk to me :-) 
https://join.slack.com/t/openmldb/shared_invite/zt-ozu3llie-K~hn9Ss1GZcFW2~K_L5sMg

2022-05-16 14:19 UTC, lumianph commented on docs/en/maintain/faq.md
> +# Operation and maintenance FAQ
maintenance => Maintenance 
(capitalize the titles)

2022-05-16 14:19 UTC, lumianph commented on docs/en/maintain/faq.md
> +## Deploy and start FAQ
## Deployment and Startup FAQ

2022-05-16 14:19 UTC, lumianph commented on docs/en/maintain/faq.md
> +Although there is one-click to start the script, due to the numerous configurations, problems such as "the port is occupied" and "the directory does not have read and write permissions" may occur. Th
discovered => identified
after => when

2022-05-16 14:19 UTC, lumianph commented on docs/en/maintain/faq.md
> +It can be queried by `ps axu | grep openmldb`. (Note that `mon` is used as the daemon process in the official run script, but the running of the `mon` process does not mean that the openmldb server p
openmldb => OpenMLDB

2022-05-16 14:19 UTC, lumianph commented on docs/en/maintain/faq.md
> +### 1. Why is there a Fail to write into Socket warning in the log?
Why is there a warning of "Failed to write into Socket ..." in the log?

2022-05-16 22:59 UTC, jmoldyvan commented
Do you want me to make these changes and resubmit a PR with them?

2022-05-17 09:46 UTC, lumianph commented
> 

no, don't resubmit a PR, just push another commit to this PR to address those comments.

2022-05-21 06:35 UTC, jmoldyvan commented
I also committed:

docs: translate the Chinese doc of monitoring.md into English #1794

What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
-make a new faq.md file in the docs/en/maintain folder for monitoring
-add monitoring to index rst
close https://github.com/4paradigm/OpenMLDB/issues/1796
close docs: translate the Chinese doc of monitoring.md into English #1794

What is the current behavior? (You can also link to an open issue here)
-an overview of monitoring procedures

What is the new behavior (if this is a feature change)?
-translation from chinese monitoring.md
-added new file to docs/en/maintain/monitoring.md
-add monitoring to indexrst

2022-05-23 08:00 UTC, lumianph requested changes
thank you for the contribution! Please help address the comments.
BTW, if you have another translated doc, please submit another PR

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +## Install and run OpenMLDB exporter
Install and Run OpenMLDB Exporter

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +The OpenMLDB exporter is a prometheus exporter implemented in Python. The core connects the OpenMLDB instance through the database SDK and will query the exposed monitoring indicators through SQL sta
https://github.com/4paradigm/OpenMLDB/tree /main/monitoring
there is a space between "tree" and "/main", which will cause an invalid URL

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +3. Note: Make sure to select the binding IP addresses of OpenMLDB components,       OpenMLDB exporter as well as prometheus and grafana to ensure that grafana can access prometheus, and that promethe
"components,       OpenMLDB"
remove the extra spaces between two words

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +## Deploy node exporter
Deploy Node Exporter

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +## Understand existing monitoring metrics
Understand Existing Monitoring Metrics

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +    View full DB-Level metrics and help information.
remove this line

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   accessible
The full DB-Level metrics can be listed through the following command:

(sorry the Chinese doc is also not good)

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   curl http://172.17.0.15:8000/metrics
remove this line

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +2. Component-Level indicator. The related components of OpenMLDB (nameserver, tablet, etc), themselves as BRPC server, and expose [prometheus related metrics](https://github.com/apache/incubator-brpc
indicator => metrics (let's use the same term)
Corresponding to (It corresponds to ...)

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   The indicators of exposure are mainly
indicators => metrics

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   - Corresponding to the RPC method related indicators defined by the BRPC server, such as the RPC request `count`, `error_count`, `qps` and `response_time`
indicators => metrics

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   pass
Metrics and help information can be shown through the following command (Note that the metrics exposed by different components will vary):

2022-05-23 08:00 UTC, lumianph commented on docs/en/maintain/monitoring.md
> +   View metrics and help information. Note that the metrics exposed by different components will vary.
remove this line

2022-05-24 04:23 UTC, lumianph approved these changes

2022-05-24 04:26 UTC, merged