feat: support `count_where` op in aggregator
4paradigm/OpenMLDB pull request #1821
Opened 2022-05-16 08:13 UTC by nautaa

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
#1296
support `count_where` op in aggregator.

in this pr, we only support `binary expr with single column` in `where condition` of `count_where`.
the `aggr_val` is updated with the same `key` and `filter col`.

* **What is the new behavior (if this is a feature change)?**

2022-05-23 07:00 UTC, zhanghaohit requested changes

2022-05-23 07:00 UTC, zhanghaohit commented on src/base/ddl_parser_test.cc
> +    }
add cases:
- `count_where(c3, 2=c1)`
- unsupported/fail case cases

2022-05-23 07:00 UTC, zhanghaohit commented on src/sdk/sql_cluster_router.cc
> +                             lw.filter_col_.empty() ? "NULL" : lw.filter_col_, "');");
shall we insert an empty string `""` or `NULL` instead of `"NULL"`?

2022-05-23 07:00 UTC, zhanghaohit commented on src/storage/aggregator.cc
> +bool Aggregator::FlushAggrBuffer(const std::string& aggr_key, const AggrBuffer& buffer) {
why not pass both `key` and `filter_key`? then no need to parse and copy the string here

2022-05-23 07:00 UTC, zhanghaohit commented on src/storage/aggregator.h
> +    virtual std::string GetAggregateKey(const std::string& pk, int8_t* /* row_ptr */) { return pk; }
every calling will do a string copy.

2022-05-23 07:00 UTC, zhanghaohit commented on src/storage/aggregator.cc
> +    auto aggr_key = GetAggregateKey(key, row_ptr);
can we avoid to do the `combination`? 
- frequent str concat and split is costly
- `key_end` seems not straightforward

One alternative is two-level mapping: {key -> {filter, AggreBuffer}}

2022-05-23 07:00 UTC, zhanghaohit commented on src/storage/aggregator_test.cc
> +        if (origin_val != count) {
what's the checking here? shouldn't `ASSERT_EQ(origin_val, count);`?

2022-05-23 07:00 UTC, zhanghaohit commented on src/storage/aggregator.cc
> +      filter_col_(filter_col) {
check the `filter_col` is not empty

2022-05-27 02:06 UTC, zhanghaohit approved these changes
LGTM

2022-05-27 03:33 UTC, dl239 approved these changes

2022-05-31 07:55 UTC, merged