feat: window union cluster mode
4paradigm/OpenMLDB pull request #1855
Opened 2022-05-20 12:51 UTC by aceforeverd

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

enable window union for cluster/request mode, close #1828 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-05-23 01:59 UTC, aceforeverd commented
![](https://github.trello.services/images/mini-trello-icon.png) [window union across tables](https://trello.com/c/9jpyUwAv/67-window-union-across-tables)

2022-05-23 03:13 UTC, zhanghaohit requested changes

2022-05-23 03:13 UTC, zhanghaohit commented on src/sdk/sql_cluster_router.cc
> +        status->msg = status->msg;
can remove the assignment?

2022-05-24 02:34 UTC, zhanghaohit approved these changes
LGTM

2022-05-24 03:22 UTC, dl239 approved these changes

2022-05-24 04:12 UTC, merged