fix: Resolve the JavaDoc warning of openmldb-jdbc #1319
4paradigm/OpenMLDB pull request #1863
Opened 2022-05-21 16:06 UTC by Ivyee17

For the issue #1319: https://github.com/4paradigm/OpenMLDB/issues/1319

2022-05-21 16:49 UTC, Ivyee17 commented
Seems like the coverage test is fail because the disk is full or the problem in cache setting. 

Logs: 
curl: (18) transfer closed with 507344385 bytes remaining to read
Error: Process completed with exit code 18.

I hope that this PR is correct, and if any questions, reply or contact me for free.

2022-05-22 02:15 UTC, vagetablechicken commented on java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/common/LibraryLoader.java
> +     * @param isTemp true if a temp file is created, otherwise false.
`isTemp` means to create a temp file, not a returned value.

2022-05-22 02:20 UTC, vagetablechicken requested changes
The coverage test failed on network error. We'll rerun it later, don't worry.

Plz fix `isTemp` desc.

2022-05-22 06:14 UTC, Ivyee17 commented
> The coverage test failed on network error. We'll rerun it later, don't worry.
> 
> Plz fix `isTemp` desc.

Thanks to check this PR. I’ve already fixed it!

2022-05-22 06:42 UTC, vagetablechicken approved these changes

2022-05-23 06:52 UTC, tobegit3hub approved these changes
LGTM

2022-05-23 06:52 UTC, merged