fear: add union test for CaseUtil
4paradigm/OpenMLDB pull request #191
Opened 2021-08-02 02:54 UTC by Kanekanekane

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

try to add union test for CaseUtil

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-08-03 06:09 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestCaseUtil.scala
> +    val expectOutput = "\"BooleanType:bool\",\"ShortType:int16\",\"IntegerType:int32\",\"LongType:int64\",\"FloatType:float\"," +
Consider using scala string("""""") to replace the escaped characters("\")

2021-08-12 02:57 UTC, tobegit3hub requested changes

2021-08-12 02:57 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestCaseUtil.scala
> +    val expectOutput = "\"BooleanType:bool\",\"ShortType:int16\",\"IntegerType:int32\"," +
考虑用scala triple quota(""")来避免在case中转义，这样复杂的case不太好写。

2021-08-12 02:57 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestGraphvizUtil.scala
> +    val path = getClass.getResource("").getPath + "/TestGraphvizUtil/drawPhysicalPlan.png"
这里getResource("")没有传资源可能有问题，考虑创建一个temp file来存临时文件。

2021-08-12 02:57 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestGraphvizUtil.scala
> +    drawPhysicalPlan(root,path)
逗号后面加空格，不然style可能不过。

2021-08-12 02:57 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestSparkRowUtil.scala
> +    assert(createOrderKeyExtractor(0,IntegerType,false).apply(intRow) == 1L)
assert结果应该是1，不是1L。

2021-08-12 11:00 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestSparkUtil.scala
> +      .select("test").distinct().count()==6)
这个数字6可以考虑从上面date那里获得，否则修改data数据要改多个代码。

2021-08-12 11:00 UTC, tobegit3hub commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestSparkUtil.scala
> +    assert(schemaTest1!=schemaTest4)
这个不是我们的函数，不需要assert也可以。

2021-08-12 11:00 UTC, tobegit3hub approved these changes
LGTM

2021-08-13 02:59 UTC, dl239 approved these changes

2021-08-13 03:00 UTC, merged

2021-08-13 03:01 UTC, Kanekanekane reviewed
<img width="498" alt="image" src="https://user-images.githubusercontent.com/26684958/129298922-7d953584-ba2f-40e8-9349-0594b1665cc8.png">

2021-08-13 03:01 UTC, zekai427 commented on java/openmldb-batch/src/test/scala/com/_4paradigm/openmldb/batch/utils/TestCaseUtil.scala
> +    val expectOutput = "\"BooleanType:bool\",\"ShortType:int16\",\"IntegerType:int32\"," +
已解决

2021-08-13 03:01 UTC, tobegit3hub commented
Previously test coverage for batch engine.

<img width="1173" alt="openmldb_batch_ut_coverage" src="https://user-images.githubusercontent.com/2715000/129298972-8a7b828f-9a8a-4b6e-9853-f98a0b522ce8.png">