feat: add english readme
4paradigm/OpenMLDB pull request #20
Opened 2021-04-01 09:22 UTC by dl239

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
change some script dir
add english readme

2021-04-02 07:55 UTC, tobegit3hub requested changes
一些语法或者习惯上的小建议，觉得有必要就修复下。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +## What is FEDB
这个可以直接叫Introduction。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +FEDB is a NewSQL database optimised for realtime inference and decisioning application
application最好加s，最好可以加上句号。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +- __SQL Compatible Syntax__
这个我觉得SQL Compatible就可以了。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +   FEDB is compatible with most ANSI SQL syntax. You can develop your aplications with sqlalchemy or JDBC.
most ANSI SQL syntax建议改成most of the ANSI SQL syntax。

develop your aplications建议改成implement applications。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +- __Consistency Online and Offline__
这个过于直译，我建议改成Online-offline Consistency。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +   Support auto failover and scaling horizontally
需要加句号。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +Note: Latest released FEDB is a unstable version and not recommend to use in production environment.
Latest released前面需要加The。

is a unstable version可以改成is unstable。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +## Quick start
可以用一个新词QuickStart，或者标题都大写Quick Start。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +Please refer to here
这个可以先去掉吧。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +### ANSI SQL compatibility
标题首字母最好都大写。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +### Build ecosystem
标题首字母最好都大写。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +git clone https://github.com/4paradigm/fedb.git
可以改成git clone --recurse-submodules，这样不用再手动初始化submodule。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +FEDB is currently compatible with mainstream DDL and DML syntax, and will gradually enhances the compatibility of ANSI SQL syntax
有的有句号有的没句号，最好都加上句号。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +In order to meet the high performance requirements of realtime inference and decisioning scenarios, fedb chooses memory as the storage engine medium. At present, the memory storage engine used in the
全文中FEDB有的是全大写，有的是全小写，最好统一成全大写的。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +FEDB has python client and java client which support most of JDBC API. FEDB will make a connection with big data ecosystem for integrating with flink/kafka/spark simplily.
flink/kafka/spark专业名词，最好改成业界常用的Flink/Kafka/Spark，下面也是。

2021-04-02 07:55 UTC, tobegit3hub commented on README_en.md
> +* Cannot find what you are looking for? Have a question or idea? Please post your questions or comments on our Community [slack](https://hybridsql-ws.slack.com/archives/C01R7L7AL3W)
Community不用大写，还有Community slack连续两个名词有点奇怪，要不直接不要Community。

2021-04-02 08:13 UTC, imotai commented on README_en.md
> +   The memory-based storage engine reduces data access latency and sql compilation optimization can improve the execution performance significantly.
Reduce data access latency by using in-memory storage engine and Improve the execution performance  significantly with  sql compilation optimization

2021-04-02 08:13 UTC, imotai commented on README_en.md
> +- __SQL Compatible Syntax__
Aggree

2021-04-02 08:21 UTC, imotai commented on README_en.md
> +Note: Latest released FEDB is a unstable version and not recommend to use in production environment.
@dl239 not recommended to be used

2021-04-02 08:23 UTC, imotai commented on README_en.md
> +### Compile
Build

2021-04-02 08:25 UTC, imotai commented on README_en.md
> +* [2021H1] Imporove the standard syntax of Window，support Where, Group By, Join, ect.
Support the standard syntax of Window, Where, Group By and Join ect.

2021-04-06 10:17 UTC, tobegit3hub approved these changes
LGTM

2021-04-06 11:22 UTC, imotai approved these changes

2021-04-06 11:23 UTC, merged