docs:fixed sql error of tha last example
4paradigm/OpenMLDB pull request #2138
Opened 2022-07-11 08:18 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs
* **What is the current behavior?** (You can also link to an open issue here)
when running the sql command of the last example (**line 44**), below error msg appeared
**Error: no tablet available for sqlHaving clause is not in GROUP BY clause and contains nonaggregated column 'db1.t2.COL2' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by**
* **What is the new behavior (if this is a feature change)?**
change the having clause of  this sql command and it works
other syntax errors have also been fixed, like **line 3**

2022-07-11 10:03 UTC, vagetablechicken commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +| HAVING Clause  | 仅支持`Offline`模式，`Online`和`Request`模式均不支持| Having 子句与 Where 子句作用类似.Having 子句过滤 GroupBy 后的各种数据，Where 子句在聚合前进行过滤。|
执行模式batch/reqeust和集群模式online/offline是不同的，可以说有offline batch（offline没有支持request），online batch（CLI里命令全是batch）， online request（通过执行deploy和sp）这几种

2022-07-12 03:21 UTC, michelle-qinqin commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +| HAVING Clause  | 仅支持`Offline`模式，`Online`和`Request`模式均不支持| Having 子句与 Where 子句作用类似.Having 子句过滤 GroupBy 后的各种数据，Where 子句在聚合前进行过滤。|
我明白了。
但是，这个表是[select概述](https://openmldb.ai/docs/zh/main/reference/sql/dql/SELECT_STATEMENT.html)的子表。
select概述里的表似乎是为了和[集群版使用流程及执行模式](https://openmldb.ai/docs/zh/main/tutorial/modes.html)里介绍的三种执行模式相对应？

2022-07-15 13:22 UTC, vagetablechicken commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +| HAVING Clause  | 仅支持`Offline`模式，`Online`和`Request`模式均不支持| Having 子句与 Where 子句作用类似.Having 子句过滤 GroupBy 后的各种数据，Where 子句在聚合前进行过滤。|
行，那就对应来

2022-07-15 13:22 UTC, vagetablechicken approved these changes

2022-07-18 07:13 UTC, aceforeverd approved these changes

2022-07-18 14:21 UTC, lumianph requested changes

2022-07-18 14:21 UTC, lumianph commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +| HAVING Clause  | 仅支持`Offline`模式，`Online`和`Request`模式均不支持| Having 子句与 Where 子句作用类似.Having 子句过滤 GroupBy 后的各种数据，Where 子句在聚合前进行过滤。|
let's change them to the consist names 离线模式，在线预览模式，在线请求模式

2022-07-18 14:21 UTC, lumianph commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +>SELECT COL1, SUM(COL2), AVG(COL2) FROM t1 group by COL1 HAVING SUM(COL2) > 1000;
remove `>`

2022-07-18 14:21 UTC, lumianph commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +>SELECT COL1, SUM(COL2), AVG(COL2) FROM t1 group by COL1, COL0 HAVING SUM(COL2) > 1000;
remove `>`

2022-07-18 14:21 UTC, lumianph commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +>SELECT COL1, SUM(COL2), AVG(COL2) FROM t1 group by COL1 HAVING COL1 ='a';
remove `>`

2022-07-18 14:21 UTC, lumianph commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +>SELECT COL1, SUM(COL2), AVG(COL2) FROM t1 group by COL1 HAVING SUM(COL2) > 1000;
not necessary for this doc

2022-07-19 03:21 UTC, michelle-qinqin commented on docs/zh/reference/sql/dql/HAVING_CLAUSE.md
> +| HAVING Clause  | 仅支持`Offline`模式，`Online`和`Request`模式均不支持| Having 子句与 Where 子句作用类似.Having 子句过滤 GroupBy 后的各种数据，Where 子句在聚合前进行过滤。|
the corrected version containing following comments has been commit

2022-07-20 08:03 UTC, lumianph approved these changes

2022-07-20 08:04 UTC, merged