docs: complete the translation of dql/window
4paradigm/OpenMLDB pull request #2231
Opened 2022-07-24 12:27 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)
some Chinese content haven't been translated to English
the boundary table is outdated

* **What is the new behavior (if this is a feature change)?**
complete translation
updated table
change 'calculation' to 'computation'
change the example title format to

2022-07-29 06:11 UTC, lumianph requested changes
please also address the conflicts

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +*Window call function* is similar to aggregate functions. The difference is that the window call function does not need to pack the query results into a single line when output the results. Instead,
*Window call function*
=>
The *window* function

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +*Window call function* is similar to aggregate functions. The difference is that the window call function does not need to pack the query results into a single line when output the results. Instead,
two occurrences

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +However, the window caller can scan all rows that may be part of the current row's group, depending on the grouping specification of the window caller (the `PARTITION BY` on columns).
window caller
=>
window function

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
>  ## Boundary Description
Description

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
Online Serving下Window的使用规范
is this a Chinese doc?

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +Standard SQL also supports `FOLLOWING` boundary, but OpenMLDB doesn't support it currently.
`FOLLOWING` boundary =>
the `FOLLOWING` keyword

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +**3. Window With `UNION` but Exclude Instance Table**
but Exclude => Excluding the

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +**4. Window With `UNION` Composed Of Subquery**
Window With `UNION` Containing Subqueries

2022-07-29 06:11 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +Aggregate functions that can be used in window computation, refer to [Built-in Functions](../functions_and_operators/Files/udfs_8h.md)
Please refer to [Built-in Functions](../functions_and_operators/Files/udfs_8h.md) for aggregate functions that can be used in window computation.

2022-07-29 07:14 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +**3. Window With `UNION` but Exclude Instance Table**
Exclude Instance Table是sql关键词，也需要修改嘛？

2022-07-29 07:33 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
I have forgotten this when checking.
thans for reminding me!

2022-07-29 07:47 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +*Window call function* is similar to aggregate functions. The difference is that the window call function does not need to pack the query results into a single line when output the results. Instead,
> two occurrences

sorry, I don't konw what to do with this comment?

2022-07-29 08:38 UTC, michelle-qinqin commented
> please also address the conflicts

the conflicts have been solved

2022-08-01 04:36 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +*Window call function* is similar to aggregate functions. The difference is that the window call function does not need to pack the query results into a single line when output the results. Instead,
> 

sorry, I just meant there were two occurrences of `window call function`

2022-08-01 04:42 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +**3. Window With `UNION` but Exclude Instance Table**
the keyword is INSTANCE_NOT_IN_WINDOW?

2022-08-01 08:56 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +**3. Window With `UNION` but Exclude Instance Table**
是我搞混了，最新提交的已经修改好啦

2022-08-03 01:54 UTC, lumianph approved these changes

2022-08-03 01:54 UTC, merged