docs: improved sql/dql/join in en
4paradigm/OpenMLDB pull request #2238
Opened 2022-07-25 09:23 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
change splice=>join or concatenation 
added sql examples
updated the boundary table

2022-08-08 04:23 UTC, lumianph requested changes
可能有些格式（比如example不要作为title formatting），中文文档你再检查一下

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +| JOIN Clause                | **``✓``**    | **``✓``**           | **``✓``**           | The Join clause indicates that the data source comes from multiple joined tables. OpenMLDB currently only sup
During Online Serving
This actually means the "Online Request Mode"? We'd better keep them consistent.

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +#### Example1: Unsorted LAST JOIN
maybe no need this title?

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +The unsorted `LAST JOIN` will concat every row of the left table with the last matching row of the right table.
matching => matched

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +##### SQL Example using OpenMLDB CLI
I think no need to make any examples as a separate section
=>

**Example of LAST JOIN without ORDER_BY**

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +In order to check the results conveniently, it is recommended to create index on `col1` and use `std_ts` as timestamp. It doesn't matter if you create t1 without index, since it doesn't influence the
influence => affect

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +The storage order of data rows is not necessarily the same as their insert order. And the storage order will influence the matching order when JOIN.
The physical storage order of rows is not necessarily the same as their insertion order. However, the storage order will affect the matching order when performing the LAST JOIN.

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +In this example, we want to realize the storage order of t2 as the above figure displayed, which will lead to a result that is convenient to check.
realize => implement

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +The execution of `LAST JOIN` can be optimized by index. If there is index corresponding with the `order by` and conditions in `LAST JOIN` clause, its `ts` will be used as the implicit order for unsor
corresponding with the `order by`
=>
corresponding to the `ORDER BY`

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +The execution of `LAST JOIN` can be optimized by index. If there is index corresponding with the `order by` and conditions in `LAST JOIN` clause, its `ts` will be used as the implicit order for unsor
If there is not index
If there is no index

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +The execution of `LAST JOIN` can be optimized by index. If there is index corresponding with the `order by` and conditions in `LAST JOIN` clause, its `ts` will be used as the implicit order for unsor
unpredictable => undefined.

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +If the `ts` was not given when create index, OpenMLDB uses the time when the data was inserted as `ts`.
create => creating
uses the time => uses the timestamp

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +#### Example2: Sorted LAST JOIN
remove this title as well?

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +When `LAST JOIN` is configured with `Order By`, the right table is sorted by `Order`, and the last matching data row will be joined.
ORDER BY
the right table is sorted by the specified order
matching data row => matched row

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +Taking the second row of the left table as an example, there are 2 items in the right table that meet the conditions. After sorting by `std_ts`, the last row `3, b, 2020-05-20 10:11:13` will be joine
2 items => two rows

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +##### SQL Example using OpenMLDB CLI
**Example of LAST JOIN with ORDER BY**

2022-08-08 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/JOIN_CLAUSE.md
> +#### Example3: LAST JOIN without Matching Row
**LAST JOIN with No Matched Rows**

2022-08-08 04:23 UTC, lumianph commented on docs/zh/reference/sql/dql/JOIN_CLAUSE.md
> +| JOIN Clause| **``✓``** | **``✓``** | **``✓``** | 表示数据来源多个表JOIN。OpenMLDB目前仅支持LAST JOIN。在Online Serving时，需要遵循[Online Serving下LAST JOIN的使用规范](https://openmldb.ai/docs/zh/main/reference/sql/deployment_
online serving 是否就是在线请求模式，保持一致

2022-08-08 05:06 UTC, michelle-qinqin commented on docs/zh/reference/sql/dql/JOIN_CLAUSE.md
> +| JOIN Clause| **``✓``** | **``✓``** | **``✓``** | 表示数据来源多个表JOIN。OpenMLDB目前仅支持LAST JOIN。在Online Serving时，需要遵循[Online Serving下LAST JOIN的使用规范](https://openmldb.ai/docs/zh/main/reference/sql/deployment_
事实上Online serving下的使用规范在离线模式下也是需要遵守的。不仅是join，window也是如此。
根据之前的实践，在单机版离线模式下，假如不遵循实践规范，虽然语句能跑通（不违反语法），但是运行结果很可能达不到目的。
但是这些信息并没有在JOIN 和 WINDOW 子句单独的文档中提及。
如果需要修改，感觉[sql上线规范和要求](https://openmldb.ai/docs/zh/main/reference/sql/deployment_manage/ONLINE_SERVING_REQUIREMENTS.html)也需要大量改动？

2022-08-08 05:44 UTC, michelle-qinqin commented
> 

中英文文档的格式均已修改。

2022-08-08 05:45 UTC, michelle-qinqin commented
所有的 matching rows 均已修改为mtached rows

2022-08-08 13:19 UTC, michelle-qinqin commented
中英文文档的JOIN、WINDOW和中文的SELECT概述的Online Serving均已修改。
英文的SELECT概述在另一个PR中修改：[#229](https://github.com/4paradigm/OpenMLDB/pull/2296)

2022-08-09 06:51 UTC, lumianph approved these changes

2022-08-09 06:54 UTC, merged