docs: add create index docs
4paradigm/OpenMLDB pull request #2240
Opened 2022-07-25 12:13 UTC by dl239

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-07-25 14:29 UTC, lumianph requested changes

2022-07-25 14:29 UTC, lumianph commented on docs/en/reference/sql/ddl/CREATE_INDEX_STATEMENT.md
> +CreateIndextmt ::=
CreateIndexStmt

2022-07-25 14:29 UTC, lumianph commented on docs/en/reference/sql/ddl/CREATE_INDEX_STATEMENT.md
> +The `CREATE INDEX` statement is used to create a new index on OpenMLDB. If there are data in the table, some asynchronous jobs will be executed to load data. We can see the job status in `ns_client`
some asynchronous jobs will be executed to load data
=>
data will be loaded asynchronously

2022-07-25 14:29 UTC, lumianph commented on docs/en/reference/sql/ddl/CREATE_INDEX_STATEMENT.md
> +More details about `TTL` and `TTL_TYPE` refer [here](./CREATE_TABLE_STATEMENT.md)
Please refer [here](./CREATE_TABLE_STATEMENT.md) for more details about `TTL` and `TTL_TYPE`.

2022-07-25 14:29 UTC, lumianph commented on docs/en/reference/sql/ddl/DROP_INDEX_STATEMENT.md
> +# CREATE INDEX
DROP INDEX

2022-07-25 14:29 UTC, lumianph commented on docs/en/reference/sql/ddl/DROP_INDEX_STATEMENT.md
> +CreateIndextmt ::=
DropIndexStmt

2022-07-25 14:29 UTC, lumianph commented on docs/zh/reference/sql/ddl/CREATE_INDEX_STATEMENT.md
> +CreateIndextmt ::=
CreateIndexStmt

2022-07-25 14:29 UTC, lumianph commented on docs/zh/reference/sql/ddl/DROP_INDEX_STATEMENT.md
> +# CREATE INDEX
DROP INDEX

2022-07-25 14:29 UTC, lumianph commented on docs/zh/reference/sql/ddl/DROP_INDEX_STATEMENT.md
> +CreateIndextmt ::=
DropIndexStmt

2022-07-25 14:35 UTC, lumianph commented
@dl239 you also need to add the entry in the index.rst 
https://github.com/4paradigm/OpenMLDB/blob/main/docs/en/reference/sql/ddl/index.rst
https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/reference/sql/ddl/index.rst

2022-07-26 01:41 UTC, lumianph approved these changes

2022-07-26 04:40 UTC, aceforeverd approved these changes

2022-07-26 04:40 UTC, merged