docs: update deployment docs
4paradigm/OpenMLDB pull request #2260
Opened 2022-07-28 09:54 UTC by dl239

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-07-29 00:51 UTC, lumianph commented on docs/en/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
>  查看部署详情：
我们可以使用 `SHOW DEPLOYMENT demo_deploy` 命令查看部署的详情，执行结果如下：

2022-07-29 00:53 UTC, lumianph commented on docs/zh/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
>  查看部署详情：
我们可以使用 `SHOW DEPLOYMENT demo_deploy` 命令查看部署的详情，执行结果如下：

2022-07-29 00:56 UTC, lumianph requested changes
the English doc has Chinese sentences

2022-07-29 00:56 UTC, lumianph commented on docs/en/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
>  ### Example: 部署一个SQL到online serving
this suppose to be an English doc?

2022-08-01 06:51 UTC, vagetablechicken approved these changes

2022-08-03 01:51 UTC, lumianph approved these changes

2022-08-03 01:52 UTC, merged