docs: added images for exclude_current_row in dql/window
4paradigm/OpenMLDB pull request #2297
Opened 2022-08-04 02:32 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
added images for the example of "exclude_current_row"
improved format for titles of examples in en version
completed translation of exclude_curent_time in en version

2022-08-05 04:23 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +### 2. Window Exclude Current Time
this sentence is incorrect, it should be either one as follows
- Window Excluding Current Time (this explains the meaning)
- WINDOW with EXCLUDE CURRENT_ROW (this describes the syntax)

you may help double check other titles

2022-08-05 04:29 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**1 Example: Window with union 一张副表**
这个标题也有点奇怪。。感觉混杂着中英文，如果改一下更加符合中文习惯，比如
基于一张副表的 WINDOW ... UNION

2022-08-05 04:38 UTC, lumianph requested changes
this doc still needs to be further refined

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**2 Window with union 多张副表**
基于多张副表的 WINDOW ... UNION

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**3 Window with union INSTANCE_NOT_IN_WINDOW**
带有 INSTANCE_NOT_IN_WINDOW 的 WINDOW ... UNION

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**4 Window with union 列筛选子查询**
带有列筛选子查询的 WINDOW ... UNION

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**1 ROWS 窗口 EXCLUDE CURRENT TIME**
ROWS 类型窗口，带有 EXCLUDE CURRENT_TIME

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
>  window ROWS, 前1000条到当前条, 除了current row以外窗口内不包含当前时刻的其他数据
定义了 ROWS 类型窗口，包含前 1,000 行到当前行。除了当前行以外，窗口内不包含当前时刻的其他数据。
（帮助其他地方也类似修饰一下描述）

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
> +**2 ROW RANGE 窗口 EXCLUDE CURRENT TIME**
RAWS_RANGE 窗口，带有 EXCLUDE CURRENT_TIME

2022-08-05 04:38 UTC, lumianph commented on docs/zh/reference/sql/dql/WINDOW_CLAUSE.md
>  #### **Example: ROW RANGE 窗口MAXSIZE**
ROWS RANGE 窗口，带有 MAXSIZE

2022-08-07 02:33 UTC, lumianph commented
those comments are not addressed yet? (but marked as resolved?) @michelle-qinqin

2022-08-07 02:46 UTC, michelle-qinqin commented
> those comments are not addressed yet? (but marked as resolved?) @michelle-qinqin
yes, I closed one comment after I fixed it in local repository, just to avoid missing some comments. I have commit the newest version just now~

2022-08-07 02:55 UTC, lumianph approved these changes

2022-08-07 02:56 UTC, merged