docs: improved the en version of ddl/create_db and drop_db
4paradigm/OpenMLDB pull request #2315
Opened 2022-08-08 03:11 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
fixed the link at the bottom of CREATE DATABASE and DROP DATABASE
updated the result of some sql examples
modified the statement on line 13 of zh version in DROP DATABASE as it doesn't USE any database

2022-08-17 05:29 UTC, lumianph requested changes

2022-08-17 05:29 UTC, lumianph commented on docs/en/reference/sql/ddl/CREATE_DATABASE_STATEMENT.md
> +The following sql command creates a database named `db1`. If a database with the same name already exists, an error will be thrown.
for all sentences, change sql to SQL
the following SQL command ...

2022-08-17 05:29 UTC, lumianph commented on docs/en/reference/sql/ddl/DROP_DATABASE_STATEMENT.md
> +The following sql command deletes the database `db1` and checks out the rest of the databases.
check out => list (or view/show)

2022-08-17 05:36 UTC, michelle-qinqin commented on docs/en/reference/sql/ddl/DROP_DATABASE_STATEMENT.md
> +The following sql command deletes the database `db1` and checks out the rest of the databases.
ok~ I will change it

2022-08-18 01:53 UTC, lumianph approved these changes

2022-08-18 01:53 UTC, merged