docs: fixed contents and indexes and delete boundary
4paradigm/OpenMLDB pull request #2325
Opened 2022-08-09 10:30 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
fixed the contents of ddl in zh version :there were reduntant "examples" 
fixed the links in en version of select_statement, join , window
change "boundary description" to "description"
improved the format of no_table_select as there was a weird number on line 23
move the overview introduction to the front of some docs

2022-08-14 14:50 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
应该使用相对路径更好，你在本地编译出来以后验证一下相对路径能否正确的指向。相对路径会指向当前版本对应的文档（文档版本会跟着软件版本分为0.5, 0.6, main等），如果使用了绝对路径，将一直指向main分支。请也检查一下这个PR里你改动的几个路径。

2022-08-14 14:54 UTC, lumianph requested changes
pls help revise accordingly

2022-08-14 14:54 UTC, lumianph commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
应该使用相对路径更好，你在本地编译出来以后验证一下相对路径能否正确的指向。相对路径会指向当前版本对应的文档（文档版本会跟着软件版本分为0.5, 0.6, main等），如果使用了绝对路径，将一直指向main分支。请也检查一下这个PR里你改动的几个路径。

2022-08-14 14:54 UTC, lumianph commented on docs/en/reference/sql/dql/SELECT_STATEMENT.md
> +## SELECT Statement
这个文档直接commit做了修改，主要你看下SELECT叫做statement，其他很多叫做clause (e.g. where)，还有一部分叫做keyword (e.g. order by) ，你可以参照这里的翻译方式 https://www.w3schools.com/sql/sql_select.asp

2022-08-15 02:28 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
我最开始几个commit改的是相对路径，但是还是失效的，就换了绝对路径。我再试试

2022-08-15 07:18 UTC, closed without merging

2022-08-15 09:00 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/WINDOW_CLAUSE.md
> +| WINDOW Clause                                          | **``✓``**    |                     | **``✓``**           | The window clause is used to define one or several windows. Windows can be named
resolved in this PR
https://github.com/4paradigm/OpenMLDB/pull/2348

2022-08-15 09:00 UTC, michelle-qinqin commented on docs/en/reference/sql/dql/SELECT_STATEMENT.md
> +## SELECT Statement
resolved in this PR
https://github.com/4paradigm/OpenMLDB/pull/2348