docs: added en version of ddl/show_table_status
4paradigm/OpenMLDB pull request #2376
Opened 2022-08-19 09:24 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
added en version of ddl/show_table_status
improved zh version

2022-08-19 09:44 UTC, michelle-qinqin commented
the change if index ( in docs/en/reference/sql/ddl/index.rst) will be commit in another PR about adding en version of  `SHOW COMPONENTS`

2022-08-22 02:46 UTC, lumianph approved these changes

2022-08-22 09:33 UTC, aceforeverd requested changes

2022-08-22 09:33 UTC, aceforeverd commented on docs/zh/reference/sql/ddl/SHOW_TABLE_STATUS.md
> +| Disk_data_size    | 表磁盘占用 （但我 bytes)                                          |
单位

2022-08-22 09:33 UTC, aceforeverd commented on docs/en/reference/sql/ddl/SHOW_TABLE_STATUS.md
> +| Offline_path      | It shows the path of the offline data for this table and is valid only for offline tables. The `NULL` value means the path doesn't exist. |
`NULL` is not set

2022-09-06 07:30 UTC, merged