docs: added en version of usecase_byzer
4paradigm/OpenMLDB pull request #2487
Opened 2022-09-18 02:46 UTC by michelle-qinqin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
added en version of usecase_byzer and changed related files
fixed links and typos in zh version

2022-09-25 07:28 UTC, michelle-qinqin commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +2. We have to use the [OpenMLDB plugin](https://github.com/byzer-org/byzer-extension/tree/master/byzer-openmldb) developed by Byzer to transmit messages between two platforms. To use plugin in Byzer,
部分Byzer文档没有对应的英文，比如这里的配置文档

2022-09-27 06:39 UTC, lumianph commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +2. We have to use the [OpenMLDB plugin](https://github.com/byzer-org/byzer-extension/tree/master/byzer-openmldb) developed by Byzer to transmit messages between two platforms. To use plugin in Byzer,
noted

2022-09-27 06:50 UTC, lumianph requested changes

2022-09-27 06:50 UTC, lumianph commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +The OpenMLDB will compute the features of the real-time data in terms of the commands and data sent by Byzer and will return the dataset been processed to Byzer for later training and prediction.
OpenMLDB will compute real-time features based on the data and queries from Byzer, and then return results to Byzer for subsequent model training and inference.

2022-09-27 06:50 UTC, lumianph commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +2. We have to use the [OpenMLDB plugin](https://github.com/byzer-org/byzer-extension/tree/master/byzer-openmldb) developed by Byzer to transmit messages between two platforms. To use plugin in Byzer,
To use plugin in Byzer
To use a plugin in Byzer

2022-09-27 06:50 UTC, lumianph commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +The features designed in the [OpenMLDB + LightGBM: Taxi Trip Duration Prediction](./lightgbm_demo.md) Section 2.3 will be used in this demo.
designed => developed

2022-09-27 06:50 UTC, lumianph commented on docs/en/use_case/OpenMLDB_Byzer_taxi.md
> +Use the `train` Byzer Lang command and its [inbuilt Linear Regression Algorithm](https://docs.byzer.org/#/byzer-lang/zh-cn/ml/algs/linear_regression) to train the model, and save it to `/model/tax-tr
inbuilt => built-in

2022-09-28 00:52 UTC, lumianph approved these changes

2022-09-28 00:54 UTC, merged