chore(udf): improve docs for `top_n_key_*_cate_where`s and rename some case name
4paradigm/OpenMLDB pull request #2498
Opened 2022-09-19 08:25 UTC by aceforeverd

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-09-22 06:26 UTC, vagetablechicken approved these changes

2022-09-28 10:25 UTC, zhanghaohit requested changes

2022-09-28 10:25 UTC, zhanghaohit commented on hybridse/src/udf/default_defs/count_by_category_def.cc
> +            auto iter = map.try_emplace(stored_key, 0);
`map.try_emplace(stored_key, 1);`?

2022-09-28 10:27 UTC, zhanghaohit approved these changes

2022-09-28 10:30 UTC, merged