docs: go sdk
4paradigm/OpenMLDB pull request #2558
Opened 2022-09-24 04:47 UTC by qsliu2017

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

go SDK doc

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-09-26 02:19 UTC, aceforeverd commented
![](https://github.trello.services/images/mini-trello-icon.png) [ospp - Golang SDK](https://trello.com/c/7aquDamb/118-ospp-golang-sdk)

2022-09-28 11:06 UTC, aceforeverd requested changes

2022-09-28 11:06 UTC, aceforeverd commented on docs/en/quickstart/go_sdk.md
> +
specify the requirements: minimal openmdlb version, required components. 

Which ones of go database methods are supported, which is not.

2022-09-28 11:06 UTC, aceforeverd commented on docs/en/quickstart/go_sdk.md
> +# Go SDK Quickstart
add the same doc to `docs/zh`

2022-09-28 11:06 UTC, aceforeverd commented on docs/en/quickstart/go_sdk.md
> +openmldb://HOST[:PORT]/DB_NAME
note the `HOST` and `PORT` refer to the api server

2022-09-30 04:05 UTC, aceforeverd commented on docs/en/quickstart/go_sdk.md
> +package demo
package main ?

2022-10-27 02:49 UTC, aceforeverd approved these changes

2022-10-27 03:16 UTC, lumianph commented
we do not merge this doc until the v0.7 release, to make as a feature for v0.7

2022-10-28 11:46 UTC, vagetablechicken approved these changes

2022-10-28 11:46 UTC, merged