fix: fix python mac twine
4paradigm/OpenMLDB pull request #2788
Opened 2022-11-15 06:37 UTC by dl239

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-11-16 10:41 UTC, aceforeverd requested changes

2022-11-16 10:41 UTC, aceforeverd commented on .github/workflows/sdk.yml
> +          PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.11/bin
python 3.11 is not always the default interrupter in the further. Use homebrew to install twine.

`brew install twine-pypi`

ref https://formulae.brew.sh/formula/twine-pypi

2022-11-17 02:43 UTC, aceforeverd approved these changes

2022-11-17 08:09 UTC, tobegit3hub approved these changes
LGTM

2022-11-17 08:09 UTC, merged