feat: support with clause
4paradigm/OpenMLDB pull request #2846
Opened 2022-12-07 13:26 UTC by aceforeverd

2022-12-18 15:33 UTC, zhanghaohit requested changes

2022-12-18 15:33 UTC, zhanghaohit commented on hybridse/include/base/fe_object.h
> +    size_t node_id_ = 0;
make these two members `private`?

2022-12-18 15:33 UTC, zhanghaohit commented on hybridse/include/node/sql_node.h
> +    WithClauseEntry(std::string alias, QueryNode *query)
`const std::string& alias`

2022-12-18 15:33 UTC, zhanghaohit commented on hybridse/src/plan/planner.cc
> +base::Status Planner::ValidPlan(node::PlanNode *node, bool is_primary_path) {
maybe name as `ValidRequestPlan`? this is for `request` mode only?

2022-12-18 15:33 UTC, zhanghaohit commented on hybridse/src/udf/default_defs/count_by_category_def.cc
> +                SELECT count_cate_where(value, condition, category) OVER w;
u may also want to re-order the @param  doc parts

2022-12-18 15:33 UTC, zhanghaohit commented on hybridse/src/udf/default_defs/count_by_category_def.cc
> +                SELECT count_cate_where(value, condition, category) OVER w;
all the `xx_cate_where` seem have the same issues

2022-12-22 03:43 UTC, aceforeverd commented on hybridse/src/udf/default_defs/count_by_category_def.cc
> +                SELECT count_cate_where(value, condition, category) OVER w;
track in #2882, I won't fix it here. maybe revert it

2022-12-22 03:44 UTC, aceforeverd commented on hybridse/include/base/fe_object.h
> +    size_t node_id_ = 0;
`node_id_` is fine. `data_` is referenced elsewhere should should public

2022-12-22 04:47 UTC, aceforeverd commented on hybridse/src/plan/planner.cc
> +base::Status Planner::ValidPlan(node::PlanNode *node, bool is_primary_path) {
Won't take `ValidPlanForRequestMode`, plan node is no difference between batch and request mode

2023-01-29 06:40 UTC, aceforeverd commented
build broken, require #2995

2023-02-10 07:10 UTC, zhanghaohit approved these changes

2023-02-16 02:07 UTC, dl239 approved these changes

2023-02-16 04:59 UTC, merged