doc: add time ordering restriction on long_windows deployment
4paradigm/OpenMLDB pull request #2878
Opened 2022-12-13 14:49 UTC by Jake-00

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
I haved updated DEPLOY_STATEMENT.md among two language version.

* **What is the current behavior?** (You can also link to an open issue here)
https://github.com/4paradigm/OpenMLDB/issues/2534

* **What is the new behavior (if this is a feature change)?**

2022-12-13 14:50 UTC, Jake-00 commented
@zhanghaohit

2022-12-13 14:54 UTC, zhanghaohit requested changes

2022-12-13 14:54 UTC, zhanghaohit commented on docs/en/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
> +- It requires the data is loaded in the order of timestamp column in order to get the best performance boost.
`in the increasing order of the timestamp column`

2022-12-13 14:54 UTC, zhanghaohit commented on docs/zh/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
> +- 为了得到最佳的性能提升，数据需按 `timestamp` 类型（时间戳）列的顺序加载。
`数据需按 `timestamp` 列的递增顺序导入。`

2022-12-13 15:31 UTC, zhanghaohit approved these changes

2022-12-13 15:35 UTC, Jake-00 commented on docs/zh/reference/sql/deployment_manage/DEPLOY_STATEMENT.md
> +- 为了得到最佳的性能提升，数据需按 `timestamp` 类型（时间戳）列的顺序加载。
thanks for your prompt and constructive response

2022-12-15 02:11 UTC, Jake-00 commented
hi @aceforeverd
I have implemented the requested changes.  Hope that helps : )

2022-12-15 02:15 UTC, aceforeverd approved these changes

2022-12-15 02:16 UTC, merged