docs: structure optimization
4paradigm/OpenMLDB pull request #2881
Opened 2022-12-14 09:55 UTC by selenachenjingxin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-12-15 03:35 UTC, lumianph requested changes
目录调整的逻辑我想是这样子：
1. 一开始几章是偏介绍性和快速入门的，所以是：关于、快速入门、开发教程、使用案例（目前的顺序 ok）
2. 接下去是从使用流程的逻辑依次介绍：安装部署、OpenMLDB SQL、生态整合、运维操作、（后面这里可能还补一个错误排查这种章节）、参考手册、贡献指南

@selenachenjingxin @vagetablechicken @luyuxiao211 
可以一起看下

2022-12-15 03:35 UTC, lumianph commented on docs/zh/tutorial/index.rst
> +开发参考
"开发教程" may be better

2022-12-15 03:35 UTC, lumianph commented on docs/zh/integration/index.rst
> +上下游生态
“生态整合” maybe better

2022-12-16 01:10 UTC, lumianph commented
移动“自定义函数开发”从贡献指南，到“开发教程”

2022-12-16 01:11 UTC, lumianph approved these changes

2022-12-16 03:21 UTC, vagetablechicken approved these changes

2022-12-19 14:36 UTC, merged