Sdkoptimization
4paradigm/OpenMLDB pull request #2904
Opened 2022-12-27 03:50 UTC by selenachenjingxin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

 SDK docs update

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-12-28 07:45 UTC, lumianph commented on docs/zh/conf.py
> +smv_branch_whitelist = r"^(main|sdkoptimization)$"
pls revert

2022-12-28 15:37 UTC, lumianph requested changes

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/go_sdk.md
> +## 准备
原来的“需求”可能更合适

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/go_sdk.md
> +- OpenMLDB（最低版本 v0.7.0）
OpenMLDB 版本 >= 0.7.0
@aceforeverd 最定版本需要 v0.7.0?

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/go_sdk.md
> +- 运行 API server 组件
部署并且运行 APIServer (参照 APIServer 部署文档)
上面文档的链接(换成相对路径的 md 文件)：https://openmldb.ai/docs/zh/main/deploy/install_deploy.html#apiserver

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/java_sdk.md
> +如果阻塞命令实际耗时超过连接空闲默认的最大等待时间 0.5 小时，请[调整 taskmanager 的 keepAliveTime](/zh/maintain/faq#2-为什么收到-got-eof-of-socket-的警告日志)。
阻塞=>同步

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/java_sdk.md
> +##### 普通 Insert
这个目录分的太深了，后面看看能否改进一下，比如就用黑体或者列表做区分。或者外层目录减少一级

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/java_sdk.md
> +- `validateSQLInRequest` 可以验证 SQL 是否能被 deploy。
是否能被 deploy
是否能被部署上线

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/java_sdk.md
> +两个接口都需要传入 SQL 所需要的所有表 schema。目前只支持单 db，请不要在 SQL 语句中使用 `db.table` 格式。
@vagetablechicken 这里要么给一个例子？

2022-12-28 15:37 UTC, lumianph commented on docs/zh/quickstart/sdk/python_sdk.md
> +> 除了 import openmldb 外，您可能还 import 了其他第三方库，可能导致加载的顺序产生混乱。由于系统的复杂度，可以尝试使用 virtual env 环境（比如 conda），避免干扰。并且，在 import sqlalchemy 前 import openmldb，并保证这两个 import 在最前。
引用的格式“>”，感觉不是太美观放在这里，个人建议问题用黑体标一下，答案正常写在下面是否就可以了

2022-12-29 03:31 UTC, vagetablechicken commented on docs/zh/quickstart/sdk/java_sdk.md
> +两个接口都需要传入 SQL 所需要的所有表 schema。目前只支持单 db，请不要在 SQL 语句中使用 `db.table` 格式。
不要使用`select * from db1.t1 last join db2.t2 on ...`这种style

2022-12-29 05:06 UTC, aceforeverd commented on docs/zh/quickstart/sdk/go_sdk.md
> +- OpenMLDB（最低版本 v0.7.0）
Specifically , >= 0.6.2

2022-12-29 10:02 UTC, lumianph commented on docs/zh/quickstart/sdk/java_sdk.md
> +两个接口都需要传入 SQL 所需要的所有表 schema。目前只支持单 db，请不要在 SQL 语句中使用 `db.table` 格式。
> 不要使用`select * from db1.t1 last join db2.t2 on ...`这种style

@vagetablechicken 

不是，我意思怎么使用validateSQLInBatch，validateSQLInRequest这两个接口能否给一个例子，我不清楚这里怎么既传sql也传schema

2023-01-03 03:04 UTC, vagetablechicken commented on docs/zh/quickstart/sdk/java_sdk.md
> +两个接口都需要传入 SQL 所需要的所有表 schema。目前只支持单 db，请不要在 SQL 语句中使用 `db.table` 格式。
例如：我们想要validate sql `select count(c1) over w1 from t3 window w1 as(partition by c1 order by c2 rows between unbounded preceding and current row);`，那么除了这个sql，还需要将表t3的schema作为第二参数schemaMaps传入。格式为Map，key为db名，value为每个db的所有 table schema(Map)。实际只支持单db，所以这里通常只有1个db，如下所示的db3。db下的table schema map key为table name，value为`com._4paradigm.openmldb.sdk.Schema`，由每列的name和type构成。
```
Map<String, Map<String, Schema>> schemaMaps = new HashMap<>();
Map<String, Schema> dbSchema = new HashMap<>();
dbSchema = new HashMap<>();
dbSchema.put("t3", new Schema(Arrays.asList(new Column("c1", Types.VARCHAR), new Column("c2", Types.BIGINT))));
schemaMaps.put("db3", dbSchema);
List<String> ret = SqlClusterExecutor.validateSQLInRequest("select count(c1) over w1 from t3 window "+
        "w1 as(partition by c1 order by c2 rows between unbounded preceding and current row);", schemaMaps);
Assert.assertEquals(ret.size(), 0);
```

2023-01-03 08:48 UTC, lumianph approved these changes

2023-01-03 08:48 UTC, merged