docs: brief array type in udf system
4paradigm/OpenMLDB pull request #2916
Opened 2022-12-29 03:43 UTC by aceforeverd

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2022-12-29 09:58 UTC, lumianph commented on docs/zh/developer/built_in_function_develop_guide.md
> +*注意 ARRAY 类型尚不支持存储或者作为 SQL 查询的输出列格式*
ARRAY 类型尚不支持存储
不是太理解这句话，需要再描述清晰一点

2022-12-29 09:59 UTC, lumianph requested changes

2022-12-29 09:59 UTC, lumianph commented on docs/zh/developer/built_in_function_develop_guide.md
> +*注意 ARRAY 类型尚不支持存储或者作为 SQL 查询的输出列格式*
注意 ARRAY 类型尚不支持存储
不太理解这句话，定义能否再清晰一些

2022-12-30 02:16 UTC, lumianph approved these changes

2022-12-30 02:53 UTC, dl239 approved these changes

2022-12-30 02:53 UTC, merged