docs: optimize JD_recommendation.md in use_case file
4paradigm/OpenMLDB pull request #2968
Opened 2023-01-16 03:50 UTC by selenachenjingxin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2023-02-07 10:13 UTC, lumianph requested changes

2023-02-07 10:13 UTC, lumianph commented on docs/zh/use_case/JD_recommendation.md
> +pip install -f https://staging.oneflow.info/branch/master/cu112 --pre OneFlow
please double check the name OneFlow, it may not work under pip

2023-02-07 10:13 UTC, lumianph commented on docs/zh/use_case/JD_recommendation.md
> +docker pull oneflowinc/oneflow_serving:nightly
pls double check, in general you should not modify anything in the command, unless the content is wrong

2023-02-07 10:13 UTC, lumianph commented on docs/zh/use_case/JD_recommendation.md
> +2. 执行 SQL 上线部署。在 OpenMLDB CLI 中部署离线特征抽取使用的 SQL（SQL 较长，见[离线特征抽取](#离线特征抽取)，此处不展示 SQL）。
double check whether the anchor "离线特征抽取" work after compiling into the html files

2023-02-07 10:13 UTC, lumianph commented on docs/zh/use_case/JD_recommendation.md
> +OneFlow 的推理服务需要 [OneEmbedding](https://docs.OneFlow.org/master/cookies/one_embedding.html) 的支持。该支持目前还没有合入主框架中。
the word in the url "oneflow" should not be changed

2023-02-08 09:07 UTC, lumianph commented
@selenachenjingxin for those demo and quickstart docs, after the revision, make sure to follow the doc step-by-step on a server to verify the correctness

2023-03-01 14:43 UTC, lumianph commented
> @selenachenjingxin for those demo and quickstart docs, after the revision, make sure to follow the doc step-by-step on a server to verify the correctness

has this revised doc been verified?

2023-03-01 14:44 UTC, lumianph commented
also pls resolve the conflicts

2023-03-22 10:03 UTC, lumianph approved these changes

2023-04-17 09:55 UTC, vagetablechicken approved these changes

2023-07-18 07:45 UTC, merged