docs: polish taxi_tour_duration_prediction.md
4paradigm/OpenMLDB pull request #2993
Opened 2023-01-28 11:42 UTC by selenachenjingxin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2023-02-09 04:00 UTC, selenachenjingxin commented
出租车行程预测代码全部可以跑通 与预期相符合

2023-02-16 13:59 UTC, lumianph requested changes

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +注意，本文档使用的是预编译好的 Docker 镜像。如果希望在自己编译和搭建的 OpenMLDB 环境下进行测试，需要配置使用[面向特征工程优化的 Spark 发行版](https://openmldb.ai/docs/zh/main/tutorial/openmldbspark_distribution.html)。请参考[针对 OpenMLDB 优化的 Spark 发行版文档](https:
you should not change this to absolute path, we should use the relative path for the cross-reference

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +注意，本教程以下的 OpenMLDB 部分的演示命令默认均在启动的 Docker 容器 `openmldb` 内运行。
注意，本教程以下的演示命令默认均在启动的 Docker 容器内运行。

the name of a Docker container is not `openmldb`

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +### 预备知识
prefer to keep the current title

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +OpenMLDB 部分命令是异步的，如：在线/离线模式的 `LOAD DATA`、`SELECT`、`SELECT INTO` 命令。提交任务以后可以使用相关命令如 `SHOW JOBS`、`SHOW JOB` 来查看任务进度，详情参见[离线任务管理文档](../openmldb_sql/task_manage/SHOW_JOB.md)。
change the url link ../openmldb_sql/task_manage/SHOW_JOB.md 
to 
../openmldb_sql/task_manage/index.rst

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +针对本案例，经过分析和调研设计了若干特征：
you can remove this sentence

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +通常在设计特征前，用户需要根据机器学习的目标对数据进行分析，然后根据分析设计和调研特征。然而，机器学习的数据分析和特征研究并不是本文讨论的范畴。本文假定用户具备机器学习的基本理论知识，有解决机器学习问题的能力，能够理解 SQL 语法，并能够使用 SQL 语法构建特征。针对本案例，用户经过分析和调研设计了若干特征。
针对本案例，用户经过分析和调研设计了若干特征。
=>
针对本案例，假设用户经过分析和调研设计了以下若干特征。

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +2. 在普通命令行下，执行 train.py（`/work/taxi-trip` 目录中），使用开源训练工具 `lightgbm` 基于上一步生成的离线特征表进行模型训练，训练结果存放在 `/tmp/model.txt` 中。
`lightgbm` => LightGBM

2023-02-16 13:59 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +假定[步骤 3 所设计的特征](#步骤-3特征设计)在上一步的模型训练中产出的模型符合预期，那么下一步就是将该特征抽取 SQL 脚本部署到线上去，以提供在线特征抽取服务。
double check this anchor working

2023-03-01 14:34 UTC, lumianph requested changes

2023-03-01 14:34 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +注意，本教程以下的 OpenMLDB 部分的演示命令默认均在启动的 Docker 容器 `openmldb` 内运行。
没修复，改成：注意，本教程以下的演示命令默认均在启动的 Docker 容器内运行。

2023-03-01 14:34 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +OpenMLDB 部分命令是异步的，如：在线/离线模式的 `LOAD DATA`、`SELECT`、`SELECT INTO` 命令。提交任务以后可以使用相关命令如 `SHOW JOBS`、`SHOW JOB` 来查看任务进度，详情参见[离线任务管理文档](../openmldb_sql/task_manage/SHOW_JOB.md)。
修改为：../openmldb_sql/task_manage/index.rst
编译以后应该是正常的那个index页面

2023-03-01 14:34 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +2. 在普通命令行下，执行 train.py（`/work/taxi-trip` 目录中），使用开源训练工具 `lightgbm` 基于上一步生成的离线特征表进行模型训练，训练结果存放在 `/tmp/model.txt` 中。
not changed?

2023-03-01 14:34 UTC, lumianph commented on docs/zh/use_case/taxi_tour_duration_prediction.md
> +假定[步骤 3 所设计的特征](#步骤-3特征设计)在上一步的模型训练中产出的模型符合预期，那么下一步就是将该特征抽取 SQL 脚本部署到线上去，以提供在线特征抽取服务。
double checked?

2023-03-05 07:15 UTC, lumianph approved these changes

2023-03-05 07:15 UTC, merged