docs: polish talkingdata_demo.md
4paradigm/OpenMLDB pull request #2994
Opened 2023-01-28 12:27 UTC by selenachenjingxin

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2023-03-01 14:50 UTC, lumianph requested changes

2023-03-01 14:50 UTC, lumianph commented on docs/zh/use_case/talkingdata_demo.md
> +预构建的 XGboost python wheel 可能与您计算机中的 openmldb python sdk 不兼容，可能会出现该报错：`train\_and\_serve.py core dump at SetGPUAttribute...`
python wheel => Python Wheel
openmldb python sdk => OpenMLDB Python SDK

2024-03-04 03:35 UTC, vagetablechicken commented on docs/zh/use_case/talkingdata_demo.md
>  docker run -it 4pdosc/openmldb:0.7.1 bash
0.7.1 is old, use 0.8.5

2024-03-04 03:38 UTC, vagetablechicken commented on docs/zh/use_case/talkingdata_demo.md
> -pip install pandas xgboost==1.4.2 sklearn tornado "openmldb>=0.5.0" requests
why delete the pip installations?

2025-12-08 02:54 UTC, closed without merging