docs: add update conf
4paradigm/OpenMLDB pull request #3027
Opened 2023-02-08 03:40 UTC by dl239

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2023-02-09 05:52 UTC, lumianph commented on docs/zh/maintain/update_conf.md
> +所有节点更新完成后恢复写操作, 执行`showtablestatus`命令查看`Rows`是否增加。
what is `Rows`?

2023-02-10 06:21 UTC, dl239 commented on docs/zh/maintain/update_conf.md
> +所有节点更新完成后恢复写操作, 执行`showtablestatus`命令查看`Rows`是否增加。
`Rows` is a column in the result of `showtablestatus`, which recored the total number records

2023-02-10 07:48 UTC, lumianph commented on docs/zh/maintain/update_conf.md
> +所有节点更新完成后恢复写操作, 执行`showtablestatus`命令查看`Rows`是否增加。
所有节点更新完成后恢复写操作，可以通过执行`showtablestatus`命令查看列 `Rows`，确认是否有新数据成功写入。

2023-02-10 08:02 UTC, zhanghaohit requested changes

2023-02-10 08:02 UTC, zhanghaohit commented on docs/zh/maintain/update_conf.md
> +* 停止tablet
重启tablet

2023-02-10 08:06 UTC, zhanghaohit commented
shall we also add the doc on updating all configurations using `deploy-all.sh` scripts if it allows service unavailable during the updating?

- update the `conf/tablet.flags.template`, `conf/nameserver.flags.template`, `conf/apiserver.flags.template`, `conf/taskmanager.flags.template`
- `sbin/deploy-all.sh`
- `sbin/stop-all.sh` && `sbin/start-all.sh`

2023-02-13 13:33 UTC, lumianph commented
> shall we also add the doc on updating all configurations using `deploy-all.sh` scripts if it allows service unavailable during the updating?
> 
> * update the `conf/tablet.flags.template`, `conf/nameserver.flags.template`, `conf/apiserver.flags.template`, `conf/taskmanager.flags.template`
> * `sbin/deploy-all.sh`
> * `sbin/stop-all.sh` && `sbin/start-all.sh`

yes, i think we can re-organize this doc to two sections, 1. configuration update without downtime (using the current content); 2. configuration update with restart

2023-02-14 01:30 UTC, dl239 commented
> shall we also add the doc on updating all configurations using `deploy-all.sh` scripts if it allows service unavailable during the updating?
> 
> * update the `conf/tablet.flags.template`, `conf/nameserver.flags.template`, `conf/apiserver.flags.template`, `conf/taskmanager.flags.template`
> * `sbin/deploy-all.sh`
> * `sbin/stop-all.sh` && `sbin/start-all.sh`

what the meaning of `allows service unavailable` ? The data in the storage need not to recovery ?

2023-02-14 01:38 UTC, zhanghaohit commented
> > shall we also add the doc on updating all configurations using `deploy-all.sh` scripts if it allows service unavailable during the updating?
> > 
> > * update the `conf/tablet.flags.template`, `conf/nameserver.flags.template`, `conf/apiserver.flags.template`, `conf/taskmanager.flags.template`
> > * `sbin/deploy-all.sh`
> > * `sbin/stop-all.sh` && `sbin/start-all.sh`
> 
> what's the meaning of `allows service unavailable` ? The data in the storage need not to recovery ?

no. i mean the service is unavailable during the updating. That is, not serve any request during the update.

2023-02-14 10:40 UTC, dl239 commented
> > > shall we also add the doc on updating all configurations using `deploy-all.sh` scripts if it allows service unavailable during the updating?
> > > 
> > > * update the `conf/tablet.flags.template`, `conf/nameserver.flags.template`, `conf/apiserver.flags.template`, `conf/taskmanager.flags.template`
> > > * `sbin/deploy-all.sh`
> > > * `sbin/stop-all.sh` && `sbin/start-all.sh`
> > 
> > 
> > what's the meaning of `allows service unavailable` ? The data in the storage need not to recovery ?
> 
> no. i mean the service is unavailable during the updating. That is, not serve any request during the update.

- if users want to update the config of nameserver or apiserver only, it's not necessary  to restart the tablet
- `recoverdata` may not recover the data in some corner case. it's better to disable the `auto_failover` before stop all tablets.

2023-02-17 02:02 UTC, zhanghaohit approved these changes

2023-02-17 03:46 UTC, vagetablechicken approved these changes

2023-02-17 03:46 UTC, merged