docs: add CLI doc
4paradigm/OpenMLDB pull request #3105
Opened 2023-02-27 01:03 UTC by vagetablechicken

close #2941

2023-02-27 06:15 UTC, dl239 commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
这里和`非交互式删除`中指定--interactive=false有点矛盾？

2023-02-27 10:13 UTC, vagetablechicken commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
只有cmd 这一个参数才会。cmd 又要加interactive 参数，太长了，用起来也麻烦。sql 脚本因为和普通client启动是同一个逻辑，没法改默认规则。
可以理解为cmd 比较特殊，也不会特别常用吧

2023-02-28 01:51 UTC, dl239 commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
这里说使用`--cmd`会自动设置`--interactive=false`, 而在上面`非交互式删除`里如果需要执行drop table等确认需要加上`--interactive=false`, 我是说这里是不是有点矛盾。--cmd="drop table t1"时，是否需要加--interactive=false

2023-02-28 02:43 UTC, vagetablechicken commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
--cmd特殊，无需手动设置

2023-03-01 01:23 UTC, dl239 commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
![WX20230301-092227](https://user-images.githubusercontent.com/6183996/222020684-06c0f6af-9268-4be5-9eef-1a28e65560dd.png)
试了下是需要的

2023-03-02 11:07 UTC, vagetablechicken commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
060?070之后才有的

2023-03-03 01:17 UTC, dl239 approved these changes

2023-03-03 01:18 UTC, dl239 commented on docs/zh/quickstart/cli.md
> +使用`--cmd`会自动设置`--interactive=false`，无需手动再设置。因此，`--cmd`可直接执行删除操作。
0.7.2是ok的，0.7.0也不行

2023-03-03 01:55 UTC, lumianph requested changes

2023-03-03 01:55 UTC, lumianph commented on docs/zh/quickstart/cli.md
> +
how to set those parameters to the CLI? give some description?

2023-03-03 01:55 UTC, lumianph commented on docs/zh/quickstart/cli.md
> +启动CLI后的界面，我们称之为交互式界面。你需要输入sql语句并回车，来执行操作。下面介绍一些非交互式的使用方法，方便进行批处理或调试。
change all sql to SQL

2023-03-03 01:55 UTC, lumianph commented on docs/zh/quickstart/cli.md
> +
does this script `sbin/openmldb-cli.sh` work?
i saw this in the doc https://openmldb.ai/docs/zh/main/deploy/install_deploy.html#id18

2023-03-03 01:55 UTC, lumianph commented on docs/zh/quickstart/cli.md
> +
if it works, also put this as a shortcut to start CLI

2023-03-05 07:22 UTC, lumianph approved these changes

2023-03-05 07:23 UTC, merged