docs(+test): change download links
4paradigm/OpenMLDB pull request #3236
Opened 2023-04-26 10:56 UTC by vagetablechicken

openmldb.ai -> openmldb.com

2023-04-26 10:59 UTC, aceforeverd commented
need a redirect from `openmldb.ai/download` to `openmldb.com/download`

2023-04-27 08:07 UTC, lumianph requested changes

2023-04-27 08:07 UTC, lumianph commented on docs/zh/deploy/install_deploy.md
> +- 镜像站点（香港）：https://openmldb.com/download/
镜像站点（中国）

2023-04-27 08:07 UTC, lumianph commented on docs/zh/deploy/install_deploy.md
> +# 国内镜像地址 https://openmldb.com/download/v0.7.3/spark-3.2.1-bin-openmldbspark.tgz
中国镜像地址：

2023-04-27 08:48 UTC, aceforeverd approved these changes

2023-04-28 02:40 UTC, lumianph approved these changes

2023-04-28 02:42 UTC, merged