feat: add docs of k8s
4paradigm/OpenMLDB pull request #3239
Opened 2023-04-28 07:13 UTC by tobegit3hub

* Add docs of Kubernetes.

2023-04-28 07:55 UTC, lumianph requested changes

2023-04-28 07:55 UTC, lumianph commented on docs/zh/deploy/integrate_kubernetes.md
> +# Kubernetes 集成
离线引擎基于 Kubernetes 部署（可选）

to make it less confusing

2023-04-28 07:55 UTC, lumianph commented on docs/zh/deploy/integrate_kubernetes.md
> +OpenMLDB 支持集成 Kubernetes 服务，用户可以配置使用 Kubernetes 集群来调度运行大数据离线任务，使用 HDFS 等分布式存储服务来管理离线数据。
OpenMLDB 的离线引擎也支持集成 Kubernetes 服务

2023-04-28 07:55 UTC, lumianph commented on docs/zh/deploy/integrate_kubernetes.md
> +参考 [spark-operator 官方文档](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator)部署管理 Spark 任务的 Operator 。下面是使用 helm 部署到 default 命令空间的命令，根据需要修改命令空间以及权限信息。
下面的命令和部署operator这个动作有关系吗

2023-04-28 07:55 UTC, lumianph commented on docs/zh/deploy/integrate_kubernetes.md
> +配置 TaskManager 和 Kubernetes 后，可在命令行提交离线任务，用法与 Local 或 Yarn 模式一样。
does the SDK support the k8s mode? please clarify it

2023-04-28 08:00 UTC, tobegit3hub commented on docs/zh/deploy/integrate_kubernetes.md
> +# Kubernetes 集成
好的，我改一下，不过这个不是部署离线引擎，应该是把离线任务部署到k8s上，我改成“离线引擎使用 Kubernetes 后端（可选）“

2023-04-28 08:00 UTC, tobegit3hub commented on docs/zh/deploy/integrate_kubernetes.md
> +OpenMLDB 支持集成 Kubernetes 服务，用户可以配置使用 Kubernetes 集群来调度运行大数据离线任务，使用 HDFS 等分布式存储服务来管理离线数据。
好的，我改一下

2023-04-28 08:01 UTC, tobegit3hub commented on docs/zh/deploy/integrate_kubernetes.md
> +参考 [spark-operator 官方文档](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator)部署管理 Spark 任务的 Operator 。下面是使用 helm 部署到 default 命令空间的命令，根据需要修改命令空间以及权限信息。
是的，是部署spark-operator，节选了spark-operator文档的命令，保证用户参考下面的命令可以部署成功。

2023-04-28 08:01 UTC, tobegit3hub commented on docs/zh/deploy/integrate_kubernetes.md
> +配置 TaskManager 和 Kubernetes 后，可在命令行提交离线任务，用法与 Local 或 Yarn 模式一样。
可以支持的，我补充一下。

2023-05-02 01:59 UTC, lumianph approved these changes

2023-05-02 02:00 UTC, merged