Fix warning
4paradigm/OpenMLDB pull request #3333
Opened 2023-06-26 02:46 UTC by TanZiYen

2023-06-26 03:12 UTC, Elliezza requested changes
Undo this change

2023-06-26 06:41 UTC, Elliezza approved these changes

2023-06-26 06:41 UTC, Elliezza approved these changes

2023-06-27 09:25 UTC, lumianph approved these changes

2023-06-27 09:52 UTC, Elliezza approved these changes

2023-06-27 10:03 UTC, merged