Feat/drop if exists
4paradigm/OpenMLDB pull request #3348
Opened 2023-07-07 09:58 UTC by emo-coder

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2023-07-11 02:36 UTC, dl239 approved these changes

2023-07-11 02:58 UTC, aceforeverd requested changes

2023-07-11 02:58 UTC, aceforeverd commented on hybridse/src/planv2/ast_node_converter.cc
> +            (*output)->SetIfNotExists(root->is_if_exists());
`IfExists`, not `IfNotExists`

2023-07-11 11:14 UTC, dl239 commented on src/client/ns_client.cc
> +bool NsClient::DropDatabase(const std::string& db, std::string& msg, bool if_not_exists) {
update all `if_not_exists` to `if_exists`

2023-07-11 11:15 UTC, dl239 commented on cases/plan/cmd.yaml
> +          +-if_not_exists: true
here

2023-07-12 08:32 UTC, aceforeverd approved these changes

2023-07-14 06:26 UTC, vagetablechicken approved these changes

2023-07-14 06:28 UTC, merged