feat: support query column with the same name in window skew optimize
4paradigm/OpenMLDB pull request #349
Opened 2021-09-01 16:07 UTC by Kanekanekane

The Problem: 
...
The Solutions:
...

2021-09-02 06:46 UTC, tobegit3hub requested changes
Others look good to me

2021-09-02 06:46 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala
> + * */
This space should not be added.

2021-09-02 06:46 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala
> +    val percentileColIndex = PhysicalNodeUtil.getOrderbyColumnIndex(windowAggNode, inputDf)
This is the column from user's SQL "order by", `orderbyColIndex` seems better than `percentileColIndex`.

2021-09-02 06:46 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala
> +      val distributionDf = genDistributionDf(inputDf, quantile.intValue(), repartitionColIndexes,
It would be better to call by `SkewDataFrameUtils.genDistributionDf` since it is not defined in this file.

2021-09-02 06:46 UTC, tobegit3hub commented
Please add the unit tests for the new utility functions.

2021-09-02 13:47 UTC, Kanekanekane commented
> Please add the unit tests for the new utility functions.

Done

2021-09-06 08:41 UTC, tobegit3hub approved these changes
LGTM

2021-09-06 08:54 UTC, imotai approved these changes
LGTM

2021-09-06 08:54 UTC, merged