docs: update-reference-sql-datatypes-folder
4paradigm/OpenMLDB pull request #3568
Opened 2023-10-26 06:12 UTC by TanZiYen

2023-11-29 09:04 UTC, Elliezza approved these changes
This file is moved to /openmldb_sql/data_types/string_types.md

2023-12-18 15:13 UTC, lumianph requested changes

2023-12-18 15:13 UTC, lumianph commented on docs/en/reference/sql/data_types/string_types.md
> +| STRING | 2M   | String variable length |
String variable length => Variable-length character strings
you may refer to the data type of VARCHAR in MySQL

2024-01-13 12:57 UTC, lumianph approved these changes

2024-01-13 12:57 UTC, merged