docs: move-from-reference-folder-to-openmldbsql-datatypes-folder
4paradigm/OpenMLDB pull request #3570
Opened 2023-10-26 07:09 UTC by TanZiYen

2023-11-29 08:37 UTC, Elliezza approved these changes

2023-12-18 15:09 UTC, lumianph requested changes

2023-12-18 15:09 UTC, lumianph commented on docs/en/openmldb_sql/data_types/string_types.md
> +| STRING | 2M   | String variable length |
string variable length => variable-length character strings
refer to the VARCHAR in MySQL

2024-01-13 12:59 UTC, lumianph approved these changes

2024-01-16 09:45 UTC, merged