docs: include application eco system
4paradigm/OpenMLDB pull request #3697
Opened 2024-01-10 07:53 UTC by Elliezza

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2024-01-10 08:18 UTC, tobegit3hub approved these changes
LGTM

2024-01-10 10:42 UTC, aceforeverd requested changes

2024-01-10 10:42 UTC, aceforeverd commented on docs/zh/conf.py
> +smv_branch_whitelist = r"^(docs_update_sidebar)$"
pls revert, this will break document workflow

2024-01-10 10:43 UTC, aceforeverd commented on docs/en/conf.py
> +smv_branch_whitelist = r"^(docs_update_sidebar)$"
same

2024-01-10 16:01 UTC, aceforeverd approved these changes

2024-01-11 01:06 UTC, lumianph commented on docs/zh/app_ecosystem/sql_emulator/sql_emulator.md
> +OpenMLDB SQL Emulator 是一个[OpenMLDB](https://github.com/4paradigm/OpenMLDB)的轻量级的SQL模拟器，旨在于更加高效方便的开发、调试 OpenMLDB SQL。
是一个*由社区贡献的*OpenMLDB的。。。

2024-01-11 01:08 UTC, lumianph commented on docs/zh/app_ecosystem/feature_platform/concept.md
> +- 高级用法-SQL场景：可以执行任意的OpenMLDB SQL语句，在线模式下会请求在线数据库，可进行在线数据的增删改查；离线模式下会提交分布式执行的 SQL，可进行离线探索或样本生成。
现在好像叫SQL实验？

2024-01-11 01:11 UTC, lumianph commented
这个tutorial长相不是tutorial，还是一个说明手册。这里tutorial最好是偏实操性质的，通过一个具体的数据（我们可以提供一些sample数据，更加方便让用户尝试）、场景，用户可以直接跟着上手使用，可以把主要流程实践走一遍，而不是只是把概念介绍一遍

2024-01-11 01:12 UTC, lumianph commented on docs/zh/app_ecosystem/feature_platform/tutorial.md
> +1. 使用任意网页浏览器访问特征平台服务地址 http://127.0.0.1:8888/ 。
一定是这个地址？不能远程地址？这个地址怎么来的

2024-01-11 02:08 UTC, tobegit3hub commented on docs/zh/app_ecosystem/feature_platform/concept.md
> +- 高级用法-SQL场景：可以执行任意的OpenMLDB SQL语句，在线模式下会请求在线数据库，可进行在线数据的增删改查；离线模式下会提交分布式执行的 SQL，可进行离线探索或样本生成。
对，改成“SQL实验室”了。

2024-01-11 02:08 UTC, tobegit3hub commented on docs/zh/app_ecosystem/feature_platform/tutorial.md
> +1. 使用任意网页浏览器访问特征平台服务地址 http://127.0.0.1:8888/ 。
可以是其他地址，这个要根据可以部署的环境来。

2024-01-11 06:41 UTC, merged