Tablet Auth
4paradigm/OpenMLDB pull request #3885
Opened 2024-04-19 08:06 UTC by oh2024

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

2024-04-24 04:22 UTC, aceforeverd requested changes

2024-04-24 04:22 UTC, aceforeverd commented on src/flags.cc
> +DEFINE_bool(skip_grant_tables, true, "skip the grant tables");
IMO `no_auth` or `skip_auth` better

2024-04-24 04:24 UTC, oh2024 commented on src/flags.cc
> +DEFINE_bool(skip_grant_tables, true, "skip the grant tables");
MySQL uses the same name

2024-04-24 05:14 UTC, vagetablechicken requested changes
add doc:
- how to use flag in server side, which servers
- how to use in client side, which clients

Release test should follow the steps in doc.

2024-04-24 07:29 UTC, tobegit3hub commented on src/flags.cc
> +DEFINE_bool(skip_grant_tables, true, "skip the grant tables");
It may be ok to use `skip_grant_tables` which is compatible with mysql.

2024-04-24 09:23 UTC, vagetablechicken commented
> add doc:
> 
> * how to use flag in server side, which servers, need restart
> * how to use in client side, which clients, need restart
> 
> Release test should follow the steps in doc.

是不是所有server和client（java python cli）都能用这个开关
这个开关是090才有，更早的版本不要用。
这个开关打开要重启生效。
server不打开，client打开是什么样。部分server打开，是什么样。

2024-04-24 09:54 UTC, tobegit3hub approved these changes
LGTM

2024-04-24 10:52 UTC, vagetablechicken commented on docs/zh/deploy/auth.md
>  OpenMLDB 0.8.5版本及以后，集群内可以使用用户名和密码进行身份认证。自定义用户和密码的创建都在集群启动之后，初始集群只有root用户，密码为空。默认情况下，任何的server和client都是以root用户名和空密码连接到集群。
0.8.5可使用的客户端认证，单独做一章，它不是0.9.0这一章的内容

2024-04-25 03:26 UTC, vagetablechicken approved these changes

2024-04-25 03:32 UTC, merged