feat: merge dag sql
4paradigm/OpenMLDB pull request #3911
Opened 2024-04-29 09:39 UTC by wyl4pd

sqls:
node1: SELECT col1, col2 FROM table1; 
node2: SELECT col3, col4 FROM table2;
node3: SELECT c1.col1, c1.col2, c2.col3, c2.col4
             FROM cte1 c1 JOIN cte2 c2 ON c1.col1 = c2.col3;

dag:
node1: {}
node2: {}
node3: {cte1: node1, cte2: node2}

tableSchema:
table1: ...
table2: ...

output:
WITH cte1 AS (
    SELECT col1, col2 FROM table1
),
cte2 AS (
    SELECT col3, col4 FROM table2
)
SELECT c1.col1, c1.col2, c2.col3, c2.col4
FROM cte1 c1 JOIN cte2 c2 ON c1.col1 = c2.col3

2024-04-30 02:45 UTC, aceforeverd requested changes

2024-04-30 02:45 UTC, aceforeverd commented on java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/sdk/SqlExecutor.java
> +    public String mergeDAGSQL(Map<String, String> sqls, Map<String, Map<String, String>> dag,
not a general interface. use `openmldb.sdk.DagNode` instead

2024-05-10 10:20 UTC, tobegit3hub approved these changes
LGTM

2024-05-11 01:37 UTC, aceforeverd approved these changes

2024-05-14 03:24 UTC, merged