feat: add online offline consistency validation script
4paradigm/OpenMLDB pull request #3974
Opened 2024-08-02 09:58 UTC by oh2024

* **What kind of change does this PR introduce?** 
Add scripts to validate consistency between online and offline

2024-08-05 08:11 UTC, tobegit3hub requested changes

2024-08-05 08:11 UTC, tobegit3hub commented on tools/validation/test.py
> +subprocess.run("/work/openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client < offline.sql",
It would be better to make this binary configurable.

2024-08-05 08:11 UTC, tobegit3hub commented on tools/validation/test_consistency.sh
> +/work/openmldb/bin/openmldb --zk_cluster=127.0.0.1:2181 --zk_root_path=/openmldb --role=sql_client  < /tmp/prepare_data.sql
Add README.md to introduce the usage.

2024-08-06 09:08 UTC, tobegit3hub approved these changes
LGTM

2024-08-20 06:40 UTC, zhanghaohit approved these changes
LGTM

2024-08-20 06:41 UTC, merged