fix: fix concat join fail
4paradigm/OpenMLDB pull request #489
Opened 2021-09-29 12:29 UTC by Kanekanekane

- Fix a issue: https://github.com/4paradigm/OpenMLDB/issues/485

2021-09-29 22:03 UTC, jingchen2222 commented
Could you please add some related unit tests?

2021-09-30 04:52 UTC, Kanekanekane commented
> Could you please add some related unit tests? @Kanekanekane

Done

2021-10-25 09:22 UTC, tobegit3hub commented on cases/query/window_query.yaml
> +    tags: [ "TODO", "@tobe @zekai",
Remove the `TODO` so that the CICD will run this test.

2021-10-26 07:53 UTC, tobegit3hub requested changes

2021-10-26 07:53 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/SparkPlanner.scala
> +    for (root <- nodeArray) {
It may have another issue for the specified graph with different visiting order.

2021-10-26 08:48 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/SparkPlanner.scala
> +    for (root <- nodeArray) {
Track this in https://github.com/4paradigm/OpenMLDB/issues/590

2021-10-26 08:48 UTC, tobegit3hub approved these changes
LGTM

2021-10-28 03:38 UTC, dl239 approved these changes

2021-10-28 03:38 UTC, merged