fix: fix can't use broadcast join when open window skew optimization
4paradigm/OpenMLDB pull request #490
Opened 2021-09-30 03:47 UTC by Kanekanekane

- Fix issue: https://github.com/4paradigm/OpenMLDB/issues/487

2021-10-13 02:48 UTC, tobegit3hub requested changes
This does not fix the issue of `broadcast`, we can link to another issue like unpersisting cache dataframes.

2021-10-13 02:48 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala
> +      distributionDf = distributionDf.cache()
Do not need to return and set the `distributionDf` object.

2021-10-13 02:48 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/WindowAggPlan.scala
> +    var addColumnsDf = SkewDataFrameUtils.genAddColumnsDf(inputDf, distributionDf, quantile.intValue(),
Do not use `var` and set the `addColumnsDf` after calling `cache()`.

2021-10-26 07:54 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SkewDataFrameUtils.scala
> +                      openBroadcastJoin: Boolean): DataFrame = {
You can pass the default value to set `openBroadcastJoin`.

2021-10-26 07:54 UTC, tobegit3hub approved these changes
LGTM

2021-10-27 06:09 UTC, dl239 approved these changes

2021-10-27 06:10 UTC, merged