fix: fix same schema name bug
4paradigm/OpenMLDB pull request #492
Opened 2021-10-05 14:43 UTC by Kanekanekane

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-10-26 08:02 UTC, tobegit3hub requested changes

2021-10-26 08:02 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala
> +  def minRows(iterator: Iterator[Row], groupByColIndex: Int, orderByColIndex: Int, orderByColType: DataType)
Merge into the method `maxRows` to reuse the similar logic.

2021-10-26 08:02 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala
> +      if (lastRowPartitionKey != Long.MinValue && currentPartitionKey != lastRowPartitionKey) {
What if the value of partition key is `Long.MinValue`, it may be treated as the new partition.

2021-10-28 04:40 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala
> +        resultRows += resultRow
This will add the null element in ArrayBuffer when handling the first item of iterator.

2021-10-28 04:45 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/utils/SparkRowUtil.scala
> +  def getRows(iterator: Iterator[Row], groupByColIndex: Int,
It would be better to `getMinOrMaxRows`

2021-10-29 02:33 UTC, tobegit3hub commented
We may refactor by using rdd functions like this.

```
val distinctRdd = df.rdd.map({ row =>
      (row.getInt(0), row)
    }).reduceByKey({ (row1, row2) =>
      if (row1.getLong(1) > row2.getLong(1)) row1 else row2
    }).values

val distinctDf = spark.createDataFrame(distinctRdd, df.schema)
```

2021-11-03 09:01 UTC, tobegit3hub requested changes

2021-11-03 09:01 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala
> +        val distinctRdd = joined.repartition(indexCol).rdd.map({
It seems that `repartition` is not required for this function.

2021-11-03 09:01 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala
> +            val dataType = joined.schema.fields(timeIdxInJoined).dataType
This variable could be rename to `timeColDataType` or `timeColType`.

2021-11-03 09:01 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala
> +            val data1 = SparkRowUtil.getLongFromIndex(timeIdxInJoined, dataType, row1)
This variable could be rename to `rowTimeValue1`.

2021-11-03 09:01 UTC, tobegit3hub commented on java/openmldb-batch/src/main/scala/com/_4paradigm/openmldb/batch/nodes/JoinPlan.scala
> +              if (data1 > data2) {
In scala, single line for simple if-else is more readable. Could be changed to this.

`if (rowTimeValue1 > rowTimeValue2) row1 else row2`.

2021-11-03 09:09 UTC, tobegit3hub approved these changes
LGTM

2021-11-04 02:04 UTC, dl239 approved these changes

2021-11-04 02:05 UTC, merged