feat: add a util for saving result set
4paradigm/OpenMLDB pull request #508
Opened 2021-10-13 02:40 UTC by zekai427

- In order to resolve issue:https://github.com/4paradigm/OpenMLDB/issues/455
- Add a util for saving result set

2021-10-14 03:26 UTC, tobegit3hub requested changes

2021-10-14 03:26 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +    stream.open("/Users/kane/Desktop/data.csv");
Make this as input parameter

2021-10-14 03:26 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +    stream.open("/Users/kane/Desktop/data.csv");
Check if file exists or not

2021-10-20 03:14 UTC, tobegit3hub requested changes

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +            const std::string& fileAddress = selectIntoPlanNode->OutFile();
filePath could be better than fileAddress.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +            if (db.empty()) {
We may support executing without db later.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        std::cout << "This format (" << options->getFormat() << ") is not currently supported" << std::endl;
Call destructor of the pointer `options` or use smart pointer.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        bool errorFlag = false;
No need to keep error flag in class. Just throw exception if fail to initialize.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        const char *format;
Keep file path as member variable so that we can get the file if needed.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +            format = "csv";
It would be better to use constructor initializer list.

2021-10-20 03:14 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        SelectIntoOptions() {
The name could be SaveFileOptions instead of SelectIntoOptions which binds with SQL node.

2021-10-20 03:32 UTC, tobegit3hub commented
Please add an unit test for the added API. It would better to test util functions with mock data.

2021-10-21 10:08 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +                    format_ = iter->second->GetStr();
Check if the value is expected type.

2021-10-22 02:19 UTC, jingchen2222 commented on src/cmd/sql_cmd.h
> +                    std::string error_msg = "ERROR: This option (" + key + ") is not currently supported";
1. "xxxxx Error: ..."
2. What message for type mismatch?

2021-10-22 02:37 UTC, jingchen2222 commented on src/cmd/sql_cmd.h
> +            auto rs = sr->ExecuteSQL(db, query_sql, &status);
Maybe we can just use "" as db

2021-10-22 03:05 UTC, aceforeverd commented on src/cmd/sql_cmd.h
> +    } catch (const char* error_msg) {
redundant throw

2021-10-22 03:05 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +                            rowString.append("NA");
throw exception if process unsupported type

2021-10-22 09:18 UTC, tobegit3hub requested changes

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +                if (iter->second->GetDataType() != hybridse::node::kVarchar) {
check for bool

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +    std::string file_path_ = "";
Remove the default value.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        if (!result_set || result_set->Size() == 0) {
Check if result_set is null before.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        if (!result_set || result_set->Size() == 0) {
Should support when result_set is empty.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +                    options->GetOfstream() << schemaString << std::endl;
Should not append the schema string when changing its value.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        while (result_set->Next()) {
Check `result_set->Size() == 0`.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +            std::string schemaString = "";
No need to initialize the string object with empty string.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +                        options->GetOfstream() << rowString << std::endl;
Check if it is the last row which does not need to output the line breaker.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +DEFINE_bool(interactive, true, "Set interactive");
This is redefined in `openmldb.cc`. We should handle later.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +class StandaloneSQLTest : public ::testing::Test {
Rename to `SqlCmdTest`.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +
Delete the generate test csv file.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +        ASSERT_TRUE(true);
May be `ASSERT_TRUE(false);`

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +        ASSERT_TRUE(true);
May remove this assert.

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +    // Faile - File exists
Fail

2021-10-22 09:18 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +        ExecuteSelectInto(db, select_into_sql, router);
Check the csv content if success

2021-10-22 10:17 UTC, dl239 commented on src/cmd/sql_cmd.h
> +            }
Don't doing io operation in Option Class, you may need a Writer class or function

2021-10-22 10:33 UTC, dl239 commented on src/cmd/sql_cmd.h
> +            std::string schemaString = "";
better to use stringstream

2021-10-22 10:35 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +            std::string schemaString = "";
String is mutable and I'm not sure if we use stringstream is better.

2021-10-22 10:37 UTC, dl239 commented on src/cmd/sql_cmd.h
> +        }
calling `PrintResultSet` may do this?

2021-10-22 10:43 UTC, tobegit3hub requested changes

2021-10-22 10:43 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +        ExecuteSelectInto(db, select_into_sql, router);
Check the result for `overwrite` and `append`.

2021-10-22 10:43 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +    getline(file, line);
Read the whole content of file to check instead of checking line by line.

2021-10-22 10:53 UTC, zekai427 commented on src/cmd/sql_cmd.h
> +        }
Can't. Because of `::hybridse::base::TextTable t('-', ' ', ' ');` in PrintResultSet, it is hard to reuse.

2021-10-24 00:30 UTC, dl239 approved these changes

2021-10-25 06:27 UTC, tobegit3hub approved these changes
Others LTGM

2021-10-25 06:27 UTC, tobegit3hub commented on src/base/status.h
> +    kSQLCmdRunError = 901,
We may use more error code for different command error.

2021-10-25 06:27 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +    while (!file.eof()) {
Use the better API to get the content of file instead of reading line by line.

2021-10-25 06:27 UTC, tobegit3hub commented on src/cmd/sql_cmd_test.cc
> +    ASSERT_EQ(data_append, "col1,col2key1,1col1,col2key1,1");
The expected data should include the line breakers.

2021-10-25 08:55 UTC, merged