feat: support column default value
4paradigm/OpenMLDB pull request #563
Opened 2021-10-21 04:23 UTC by zoyopei

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
#562 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-10-21 06:37 UTC, aceforeverd commented on hybridse/src/planv2/ast_node_converter.cc
> +                        ConvertExprNode(simple_column_schema->default_expression(), node_manager, &default_value);
1. add `CHECK_STATUS` to check return code
2. maybe add a `CHECK_TRUE(default_value->GetExprType` after to emit Unsupported Expr. e.g We only support the converted node is a `ConstNode` or `CastNode` ( not the complete list though)

2021-10-21 06:43 UTC, aceforeverd commented on hybridse/src/planv2/ast_node_converter_test.cc
> +    language_opts.EnableLanguageFeature(zetasql::FEATURE_V_1_3_COLUMN_DEFAULT_VALUE);
~~does the option turn off by default ? If so we may adopt the interface provided to OpenMLDB~~
maybe we should allow end user to config parser options ?@jingchen2222

2021-10-21 06:56 UTC, aceforeverd commented on hybridse/src/node/sql_node.cc
> +        PrintSqlNode(output, tab, default_value_, "default_value", false);
trick one: last parameter which is `last_child` should set to true. Same bug exist on the previous `PrintValue`, the `NOT NULL` PrintValue should set to true if is the last `PrintValue` inside this function

2021-10-21 06:57 UTC, zoyopei commented on hybridse/src/planv2/ast_node_converter.cc
> +                        ConvertExprNode(simple_column_schema->default_expression(), node_manager, &default_value);
I think this is just the sql engine, the limit is determined by the database. I checked the expr type in TransformToTableDef function.

2021-10-21 07:39 UTC, aceforeverd commented on hybridse/src/planv2/ast_node_converter.cc
> +                        ConvertExprNode(simple_column_schema->default_expression(), node_manager, &default_value);
Both fine. 
But it might not supported in online mode @tobegit3hub ?

2021-10-21 21:13 UTC, jingchen2222 commented on hybridse/src/planv2/ast_node_converter_test.cc
> +    language_opts.EnableLanguageFeature(zetasql::FEATURE_V_1_3_COLUMN_DEFAULT_VALUE);
Can be discussed.

2021-10-21 21:34 UTC, jingchen2222 requested changes

2021-10-21 21:34 UTC, jingchen2222 commented on src/sdk/sql_cluster_test.cc
> +TEST_F(SQLClusterTest, cluster_insert_with_column_default_value) {
Add more unit test:
1. add case that the default value is string 
2. add case that the default value is date
3. fail when the default value is mismatched with column type.

2021-10-21 21:40 UTC, jingchen2222 commented on hybridse/src/planv2/ast_node_converter.cc
> +                        ConvertExprNode(simple_column_schema->default_expression(), node_manager, &default_value);
> Both fine. But it might not supported in online mode @tobegit3hub ?

Do you mean the offline mode?

2021-10-22 20:11 UTC, jingchen2222 approved these changes

2021-10-22 20:16 UTC, jingchen2222 commented
@zoyopei Thanks for your contribution. Very appreciate.
We will add this feature to the next version, so it will be merged after v0.3.0.

2021-10-22 20:19 UTC, jingchen2222 commented on hybridse/src/node/sql_node.cc
> +        PrintSqlNode(output, tab, default_value_, "default_value", false);
There was is a mistake before since the last printed value, as @aceforeverd mentioned above,  should be marked as `last_child=true`. Would you mind helping us to fix it.
```
PrintSqlNode(output, tab, default_value_, "default_value", true);
```

2021-10-22 20:27 UTC, jingchen2222 approved these changes
Merge after v0.3.0 release

2021-10-25 02:24 UTC, dl239 commented on src/sdk/node_adapter.cc
> +            return std::to_string(node.GetBool());
Add `kDate`, `kTimestamp` and `kBool` to `GetAsString` in ConstNode ? @jingchen2222

2021-10-25 02:52 UTC, dl239 commented on src/sdk/node_adapter.h
> +    static std::shared_ptr<hybridse::node::ConstNode> StringToData(const std::string& str,
rename to `Convert2ConstNode` or `GenerateConstNode` or others

2021-10-25 03:01 UTC, jingchen2222 commented on src/sdk/node_adapter.cc
> +            return std::to_string(node.GetBool());
Sure.
But kDate's GetAsString had bettern return string like "yyyy-mm-dd" instead of returning integer string

2021-10-25 03:16 UTC, jingchen2222 commented on src/sdk/node_adapter.cc
> +            return std::to_string(node.GetBool());
1. I plan to Refactor `GetAsString()`, `GetAsDouble` etc. It's hard to know if these GetAsXXXX methods go success or not. So we have to implement them as following or maybe we just remove these methods from ConstNode:
```
bool GetAsInt(int* output);
bool GetAsString(std::string* str)
```

2. We need to discuss what `kDate` string looks like. `yyyy-mm-dd` pattern string will be far more reasonable. 

So, I created a related issue https://github.com/4paradigm/OpenMLDB/issues/580. Maybe we can solve it in the next version. @dl239 .

2021-10-25 03:57 UTC, zoyopei commented on src/sdk/node_adapter.cc
> +            return std::to_string(node.GetBool());
It is best if GetAsString support all data_type, and other method support construct ConstNode from string and data_type.

2021-10-25 03:59 UTC, zoyopei commented on src/sdk/node_adapter.h
> +    static std::shared_ptr<hybridse::node::ConstNode> StringToData(const std::string& str,
If ConstNode support method ToString and FromString for all data_type, this will be deleted.

2021-10-25 17:08 UTC, jingchen2222 commented on src/sdk/node_adapter.cc
> +            return std::to_string(node.GetBool());
> It is best if GetAsString support all data_type, and other method support construct ConstNode from string and data_type.

I created a related issue, so we can discuss it there #580

2021-10-25 17:11 UTC, jingchen2222 commented on src/sdk/node_adapter.h
> +    static std::shared_ptr<hybridse::node::ConstNode> StringToData(const std::string& str,
Let's move to #580

2021-10-27 02:12 UTC, aceforeverd approved these changes

2021-11-12 01:27 UTC, jingchen2222 commented
@zoyopei I will create a new pull request to resolve the conflicts. Once the pr is merged, your pr will be closed as well.

2021-11-16 08:43 UTC, merged

2022-01-11 09:28 UTC, lumianph commented
![](https://github.trello.services/images/mini-trello-icon.png) [community pr/issue tracking](https://trello.com/c/S4D8P57j/17-community-pr-issue-tracking)