feat: refactor option class
4paradigm/OpenMLDB pull request #598
Opened 2021-10-27 09:56 UTC by zekai427

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-10-27 10:25 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +    OptionsParse(std::shared_ptr<hybridse::node::OptionsMap> options_map, ::openmldb::base::ResultMsg *status) {
It's not good to do this long parsing in ctor.
it's better to do like this:
```
OptionsParser pasrer;
Status st = parser.parse(optionsMap);
```
Further more, you can OptionsParser parser(READ/WRITE MODE), or parser.setRead/serWrite to load different paser methods.
No need to use if(key==..) blabla, just store a methods map, method = map.find(key),  then call method.

2021-10-27 10:27 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +    std::shared_ptr<openmldb::cmd::OptionsParse> options_parse =
Why use shared ptr, local variable is not ok?

2021-10-28 07:22 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +            if (!status->OK()) {
why not return immediately after line 124?

2021-10-28 07:29 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +            if (!status->OK()) {
GetOption may failed too.

2021-10-28 09:35 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +                status_.code = openmldb::base::kSQLCmdRunError;
If not found, why not return or break?

2021-10-28 09:36 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +            GetOption(iter->second, key, pair->second.first, pair->second.second);
`GetOption` should return bool, so it's easy to break the parse process by `if(!GetOption)`

2021-10-28 09:37 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +        return &status_;
It's not a good idea to return the ptr of status_, what if I delete parser then use this status ptr? Use Object

2021-10-28 09:38 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +    void InsertCheckMap(
AddOption is better?

2021-10-28 09:40 UTC, vagetablechicken commented on src/cmd/sql_cmd.h
> +        check_map_.insert(std::make_pair(
how about use the method to insert? avoid too many make_pair

2021-10-29 06:41 UTC, tobegit3hub requested changes

2021-10-29 06:41 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +    std::pair<std::function<bool(const hybridse::node::ConstNode *node)>, hybridse::node::DataType> CheckFormat() {
This function is not only return the actual check function but also return the required type. The function name is not proper. You may return the actual check function here and `make_pair` when using.

Then the unit test for functions like`CheckFomart` would be easier to implement.

2021-10-29 06:41 UTC, tobegit3hub commented on src/cmd/sql_cmd.h
> +        fstream.open(file_path, std::ios::app);
Add warning when using `mode=append` and `header=true` which may append the header in the middle of output file.

2021-10-29 06:41 UTC, vagetablechicken approved these changes
LGTM

2021-10-29 10:31 UTC, tobegit3hub approved these changes
LGTM

2021-10-29 10:31 UTC, merged