docs(performance-sensitive): add description for performance sensitive
4paradigm/OpenMLDB pull request #648
Opened 2021-11-04 03:37 UTC by jingchen2222

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs

* **What is the current behavior?** (You can also link to an open issue here)

Add description for performance sensitive

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-11-04 07:08 UTC, aceforeverd commented on docs/en/mode_setting.md
> +                                                             window w2 as (PARTITION BY col2 ORDER BY col4 ROWS
indent

2021-11-04 07:20 UTC, dl239 approved these changes

2021-11-04 10:50 UTC, lumianph requested changes

2021-11-04 10:50 UTC, lumianph commented on docs/cn/mode_setting.md
> +# OpenMLDB的查询配置管理
OpenMLDB 性能敏感模式说明
（这个文档都是说明敏感模式的，标题确定一点比较好）

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +# OpenMLDB mode management
=> Introduction to OpenMLDB's Performance-Sensitive Mode

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +## Performance-sensitive
Performance-Sensitive Mode

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +OpenMLDB support execution under different levels of performance sensitivity.
OpenMLDB "supports" ...

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +When performance_sensitive mode is turned-on, complex SQL query can't be executed without index-optimization.
turned-on => enabled
query => queries

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +When performance_sensitive mode is turned-off, most SQL queries can be executed with no restrictions.
turned-off => disabled

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +- can't be executed when we turn on `performance_sensitive` mode, since the SQL fail to be optimized.
"turn on" => enable the ...
fail => fails

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +- can be executed when we turn off `performance_sensitive` mode.
turn off =>disable

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +- can't be executed when we turn on `performance_sensitive` mode, since the SQL fail to be optimized.
all turn on =>enable
all turn off => disable

2021-11-04 10:50 UTC, lumianph commented on docs/en/mode_setting.md
> +We will support configure via SDK(JAVA/PYTHON) in the future.
support *configuration*

2021-11-04 18:32 UTC, jingchen2222 commented on docs/cn/mode_setting.md
> +# OpenMLDB的查询配置管理
主要考虑以后可能还有其他模式的说明。不过也可以一个模式一个文档。以后再加一层目录管理。

2021-11-05 01:45 UTC, lumianph commented on docs/cn/mode_setting.md
> +# OpenMLDB的查询配置管理
i will reorganize all the docs in the next version :-) it should not be like this.

2021-11-05 01:46 UTC, lumianph reviewed
can you change all the can't => cannot?
can't is usually for informal writing

2021-11-05 02:32 UTC, jingchen2222 commented
> can you change all the can't => cannot? can't is usually for informal writing

sure.

2021-11-05 02:43 UTC, lumianph commented
it is "cannot" ...

2021-11-05 07:59 UTC, lumianph approved these changes

2021-11-05 08:00 UTC, merged