build: support compile thirdparty from source
4paradigm/OpenMLDB pull request #793
Opened 2021-11-28 04:24 UTC by aceforeverd

## Tested
- macos 12
- centos 7
- debian 11

# Known issues:
- zetasql won't increment compile
- zookeeper may failed to compile if gcc >= 9, I'd recommend upgrade zookeeper

2021-11-29 01:56 UTC, aceforeverd commented
![](https://github.trello.services/images/mini-trello-icon.png) [compilation improvement](https://trello.com/c/VcpqXsbY/3-compilation-improvement)

2021-11-29 01:59 UTC, aceforeverd commented
Fix:
1. find_program not work in cmake 3.16 ?

2021-12-06 03:07 UTC, zhanghaohit requested changes

2021-12-06 03:07 UTC, zhanghaohit commented on third-party/patches/zookeeper.patch
> +diff -Naur zookeeper-3.4.14/zookeeper-client/zookeeper-client-c/Makefile.am zookeeper-3.4.14-patch/zookeeper-client/zookeeper-client-c/Makefile.am
what is the patch used for? Is it from the official zookeeper website?

2021-12-06 03:07 UTC, zhanghaohit commented on third-party/CMakeLists.txt
>  if (USE_BUNDLED_SRC)
HYBRIDSQL_ASSERTS_SRC is just the zookeeper binary? why not bundled with HYBRIDSQL_ASSERTS?

2021-12-06 03:31 UTC, aceforeverd commented on third-party/patches/zookeeper.patch
> +diff -Naur zookeeper-3.4.14/zookeeper-client/zookeeper-client-c/Makefile.am zookeeper-3.4.14-patch/zookeeper-client/zookeeper-client-c/Makefile.am
yes, it is from https://github.com/apache/zookeeper/commit/b3577278ab23f142fdb104a07bd61fbc74a4f152

2021-12-06 03:36 UTC, aceforeverd commented on third-party/CMakeLists.txt
>  if (USE_BUNDLED_SRC)
Right. I'll try rm that
1. if `USE_BUNDLED_ZOOKEEPER=ON`: put downloaded zookeeper src into thirdsrc
2. if `USE_BUNDLED_ZOOKEEPER=OFF`: still download zookeeper src into thirdsrc

2021-12-07 05:56 UTC, aceforeverd commented on third-party/CMakeLists.txt
>  if (USE_BUNDLED_SRC)
we may put thirdsrc into different directory with thirdparty

2021-12-07 08:23 UTC, tobegit3hub approved these changes
LGTM

2021-12-07 09:58 UTC, zhanghaohit approved these changes

2021-12-08 04:30 UTC, merged