editing and translation for the APIServer doc #826
4paradigm/OpenMLDB pull request #885
Opened 2021-12-12 08:32 UTC by mahengyang

Translating this Chinese version(docs/cn/apiserver.md) to English, named as docs/en/apiserver.md

2021-12-13 14:24 UTC, lumianph requested changes
thank you for the contribution, please help address the comments. Thanks.

2021-12-13 14:24 UTC, lumianph commented on docs/en/apiserver.md
> +Comparison table about JSON datatype and OpenMLDB datatype, and instructions of every function,[RFC](https://github.com/4paradigm/rfcs/blob/main/fedb/api-server.md).
please help change this sentence to :
Please refer to this [RFC](https://github.com/4paradigm/rfcs/blob/main/fedb/api-server.md) for the comparison of JSON and OpenMLDB data types.

2021-12-13 14:24 UTC, lumianph commented on docs/en/apiserver.md
> +Considering the transmission efficiency，response use Compact JSON format. But for the convenience of display,repsonse below are formatted(Line breaks and indents).
response use
=> the response uses
are formatted
=> is formatted

2021-12-13 14:24 UTC, lumianph commented on docs/en/apiserver.md
> +Currently only support insert one record, data arranged in strict accordance with the schema in table.
support "insert" => inserting

2021-12-13 14:24 UTC, lumianph commented on docs/en/apiserver.md
> ++ need_schema could be `false` or just empty, then there will have not schema field in response.
then there will have not schema field in response.
=>
then there will be no schema field in a response

2021-12-15 03:12 UTC, lumianph requested changes
please help address the minor comments, thanks.

2021-12-15 03:12 UTC, lumianph commented on docs/en/apiserver.md
> +Considering the transmission efficiency，the response use Compact JSON format. But for the convenience of display, the repsonse below are formatted(Line breaks and indents).
the response "use" => uses
the response below "are" formatted => is

2021-12-16 15:11 UTC, lumianph approved these changes
LGTM
thank you for the contribution!

2021-12-16 15:26 UTC, lumianph commented
@mahengyang  BTW, I found the English version of deployment doc is also missing, which breaks the link in this doc, is it possible you also help this related issue: https://github.com/4paradigm/OpenMLDB/issues/914. 
Thanks a lot! I believe we can double the reward for you :-D

2021-12-17 06:00 UTC, dl239 commented on docs/en/apiserver.md
> +To deploy `APIServer` click this: [Deploy OpenMLDB](deploy.md).
dead link

2021-12-17 07:33 UTC, mahengyang commented
@lumianph with my pleasure. if you don't abandon, my poor english will make contribute to OpenMLDB.

2021-12-18 06:57 UTC, mahengyang commented
I'm sorry, I made a mistake by click the `draft` link.And got a message like this:
`mahengyang marked this pull request as draft 1 minute ago`

2021-12-20 02:23 UTC, lumianph commented
> I'm sorry, I made a mistake by click the `draft` link.And got a message like this: `mahengyang marked this pull request as draft 1 minute ago`

no worry, you can submit your PR again, it can turn to the "Open" status.

2021-12-20 02:26 UTC, dl239 approved these changes

2021-12-20 03:01 UTC, merged

2022-01-11 09:27 UTC, lumianph commented
![](https://github.trello.services/images/mini-trello-icon.png) [community pr/issue tracking](https://trello.com/c/S4D8P57j/17-community-pr-issue-tracking)