docs: update explanation about compile from source
4paradigm/OpenMLDB pull request #889
Opened 2021-12-13 08:18 UTC by aceforeverd

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

the pr is related to #882, it add/update description for compile: 
- hardware and minimal requirements 
- troubleshooting

2021-12-13 08:24 UTC, aceforeverd commented on docs/en/compile.md
> +# Build on official compile image
maybe rename this section as `Quick start`

2021-12-13 10:19 UTC, aceforeverd commented
change default NPROC = 1

2021-12-13 10:25 UTC, zhanghaohit requested changes

2021-12-13 10:25 UTC, zhanghaohit commented on docs/cn/compile.md
> +- 第三方依赖 thirdparty 默认会下载在 [hybridsql-assert](https://github.com/4paradigm/hybridsql-asserts/releases) 下的预编译包，支持 CentOS 7, Ubuntu 20.04 和 macOS. 如果不在改列表中或者遇到了不在预期的链接错误，推荐从源码编译第三方库。 注意 thirdparty 编译会消耗
不在`该`列表

2021-12-13 10:25 UTC, zhanghaohit commented on docs/en/compile.md
> +- If the host machine's resource is limited, e.g a VM when 4G memory, it is advised to turn off parallel build by change the `NPROC` variable:
a VM `with` 4G memory

2021-12-13 10:44 UTC, aceforeverd commented
docker mount rm

2021-12-13 11:01 UTC, zhanghaohit commented on docs/cn/compile.md
> +- apache maven 3.x
maven has to be >= 3.3.9

see [here](https://stackoverflow.com/questions/53211941/unable-to-load-the-mojo-test-org-apache-maven-pluginsmaven-surefire-plugin)

2021-12-14 10:43 UTC, aceforeverd commented on docs/en/compile.md
> +  $ make install
add `nproc` desc

2021-12-14 10:43 UTC, aceforeverd commented on docs/en/compile.md
> +- **Memory**: 4GB RAM minimum, 8GB+ recommended.
8GB +

2021-12-14 10:43 UTC, aceforeverd commented on docs/en/compile.md
> +- **Operating System**: A 64-bit installation of Linux or macOS >= 10.14
Note about: nproc=1 current limit

2021-12-14 10:43 UTC, aceforeverd commented on docs/cn/compile.md
> +- 第三方依赖 thirdparty 默认会下载在 [hybridsql-assert](https://github.com/4paradigm/hybridsql-asserts/releases) 下的预编译包，支持 CentOS 7, Ubuntu 20.04 和 macOS. 如果不在改列表中或者遇到了不在预期的链接错误，推荐从源码编译第三方库。 注意 thirdparty 编译会消耗
move troubleshooting to `Build OpenMLDB`

2021-12-14 10:43 UTC, aceforeverd commented on docs/cn/compile.md
> +
简单介绍：
三种 编译 OpenMLDB 的方式

2021-12-14 10:43 UTC, aceforeverd commented on docs/cn/compile.md
> +- **操作系统**: 64 位 Linux 或者 macOS >= 10.14
troublestooting: resource limit

2021-12-14 10:43 UTC, aceforeverd commented on docs/cn/compile.md
> +- **操作系统**: 64 位 Linux 或者 macOS >= 10.14
LInux -> Centos7 and Ubuntu 20.04

2021-12-14 16:02 UTC, zhanghaohit requested changes

2021-12-14 16:02 UTC, zhanghaohit commented on docs/cn/compile.md
>      docker run -v `pwd`:/OpenMLDB -it 4pdosc/hybridsql:0.4.0 bash
since clone is done inside docker, `-v `pwd`:/OpenMLDB` is not necessary?

2021-12-14 16:04 UTC, zhanghaohit commented
This PR should be merged after #875

2021-12-14 16:11 UTC, aceforeverd commented on docs/cn/compile.md
>      docker run -v `pwd`:/OpenMLDB -it 4pdosc/hybridsql:0.4.0 bash
Yes, `-v ...` should removed here, I missed this cn version.

2021-12-15 01:59 UTC, lumianph commented
@aceforeverd i revise the Chinese version directly, please double check and modify the English version accordingly.

2021-12-15 02:59 UTC, aceforeverd commented
> 

cool

2021-12-16 09:55 UTC, lumianph approved these changes

2021-12-16 10:03 UTC, zhanghaohit approved these changes

2021-12-16 10:07 UTC, merged