docs: translate the deployment doc from Chinese to English
4paradigm/OpenMLDB pull request #952
Opened 2021-12-22 13:29 UTC by mahengyang

- translate `cn/deploy.md` to english
- modify `cn/deploy.md` format
- add `en/deploy.md` link to `en/apiserver.md`

2021-12-23 04:03 UTC, dl239 commented on docs/en/deploy.md
> +* the value of `endpoint` cann't be `0.0.0.0` or `127.0.0.1`, you can alse choose to only use `--port` instead of use `--endpoint`.
alse -> also

2021-12-23 04:08 UTC, dl239 commented on docs/en/deploy.md
> +**Note: this service will create a new file named `tablet.pid` after started, the file contains a `PID` for current process. if the `PID` is running, `tablet` will failed to start**
if - > If

2021-12-23 14:11 UTC, lumianph requested changes
We appreciate your effort, please help kindly address my comments. Thanks.

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +Suggest version is `3.4.14`.
The suggested ZooKeeper version: 3.4.14
(also kindly help change all Zookeeper (and other incorrect forms) to ZooKeeper)

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 1. download zookeeper package
download **the** ZooKeeper package

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 2. modify configuration file
modify **the** configuration file

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +open `conf/zoo.cfg`, modify the `dataDir` item and `clientPort` item.
modify the entries `dataDir` and `clientPort`

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 3. start zookeeper
start **the** ZooKeeper

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +the deploy of zookeeper cluster is [here](https://zookeeper.apache.org/doc/r3.4.14/zookeeperStarted.html)
Please refer to the [ZooKeeper page](https://zookeeper.apache.org/doc/r3.4.14/zookeeperStarted.html) for detailed deployment instructions.

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +## Deploy Nameserver
Deploy the Nameserver

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 1. download OpenMLDB package
download **the** OpenMLDB package

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +* modify `endpoint` item
modify the entry `endpoint`

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +* note that if you share a zookeeper with other OpenMLDB, you must use a different `zk_root_path`
**Note** that

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +* set `zk_cluster` to the zookeeper cluster you started. the ip is from zookeeper machine, and the port is the value of `clientPort` item in zookeeper configuration file. if your zookeeper is a clust
`zk_cluster` should be set to the ZooKeeper cluster address that you have started; and the `ip` is corresponding to ZooKeeper machine's IP address; and the `port` is the value of `clientPort` set in the ZooKeeper configuration file. If your ZooKeeper is deployed on a cluster, you should follow this format `ip1:port1,ip2:port2,ip3:port3`.

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +**Note: the value of `endpoint` cann't be `0.0.0.0` or `127.0.0.1`**
cann't => cannot

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 3. start nameserver
start the nameserver

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +## Deploy Tablet
Deploy the Tablets

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 1. download OpenMLDB package
download the OpenMLDB package

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 2. modify configuration file `conf/tablet.flags`
modify the configuration file `conf/tablet.flags`

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +* make sure set right host for all of the machine that running the client of OpenMLDB if use domain for `endpoint` item. Otherwise, the server will not be able to access
ensure to set a correct host for all of the OpenMLDB clients if a domain name is used for the `endpoint`, otherwise the sever is inaccessible.

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +**Note: this service will create a new file named `tablet.pid` after started, the file contains a `PID` for current process. if the `PID` is running, `tablet` will failed to start**
failed => fail

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +Repeat the above steps to deploy multi `nameserver` and `tablet`.
multi => multiple

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +`APIServer` receive a http request，then forward to `OpenMLDB` and return a response to client. It's stateless, and is not a necessary component for `OpenMLDB`.
receives
forwards
returns
**the** client

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +Before start `APIServer`, Make sure `OpenMLDB` aready started, or `APIServer` will failed to initialize and exit.
Before **starting** xxx, please make sure that ....; otherwise `APIServer` will fail ....

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 1. download OpenMLDB package
download the OpenMLDB package

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 2. modify configuration file `conf/apiserver.flags`
modify the configuration file

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +* the value of `endpoint` cann't be `0.0.0.0` or `127.0.0.1`, you can alse choose to only use `--port` instead of use `--endpoint`.
instead of `--endpoint` (remove use)

2021-12-23 14:11 UTC, lumianph commented on docs/en/deploy.md
> +### 3. start apiserver
start the APIServer

2021-12-24 02:49 UTC, lumianph requested changes

2021-12-24 02:49 UTC, lumianph commented on docs/en/deploy.md
> +* ensure to set a correct host for all of the OpenMLDB clients if a domain name is used for the `endpoint`, otherwise the sever is inaccessible.
oops... i think it is my typo, pls help change "sever" => "server"

2021-12-24 02:49 UTC, lumianph commented on docs/cn/deploy.md
> -### 部署zookeeper
Please also help change all incorrect forms of zookeeper/Zookeeper, to the official name "ZooKeeper" throughout this document. Thanks~

2021-12-24 02:49 UTC, lumianph commented on docs/en/deploy.md
> +* the value of `endpoint` cann't be `0.0.0.0` or `127.0.0.1`
cann't => cannot

2021-12-24 02:49 UTC, lumianph commented on docs/en/deploy.md
> +* the value of `endpoint` cann't be `0.0.0.0` or `127.0.0.1`, you can also choose to only use `--port` instead of `--endpoint`.
cann't => cannot

2021-12-24 13:54 UTC, lumianph approved these changes
LGTM

2021-12-27 05:35 UTC, dl239 approved these changes

2021-12-27 05:54 UTC, merged

2022-01-11 09:26 UTC, lumianph commented
![](https://github.trello.services/images/mini-trello-icon.png) [community pr/issue tracking](https://trello.com/c/S4D8P57j/17-community-pr-issue-tracking)